//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../android//com/vals/a2ios/amfibian/intf/AnAdapter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComValsA2iosAmfibianIntfAnAdapter")
#ifdef RESTRICT_ComValsA2iosAmfibianIntfAnAdapter
#define INCLUDE_ALL_ComValsA2iosAmfibianIntfAnAdapter 0
#else
#define INCLUDE_ALL_ComValsA2iosAmfibianIntfAnAdapter 1
#endif
#undef RESTRICT_ComValsA2iosAmfibianIntfAnAdapter

#if !defined (AnAdapter_) && (INCLUDE_ALL_ComValsA2iosAmfibianIntfAnAdapter || defined(INCLUDE_AnAdapter))
#define AnAdapter_

@class IOSClass;
@protocol AnAttrib;

@protocol AnAdapter < JavaObject >

- (id)convertWithAnAttrib:(id<AnAttrib>)attrib
                   withId:(id)value;

- (void)onWarningWithIOSClass:(IOSClass *)cluss
                 withNSString:(NSString *)attribName
                       withId:(id)value;

@end

J2OBJC_EMPTY_STATIC_INIT(AnAdapter)

J2OBJC_TYPE_LITERAL_HEADER(AnAdapter)

#define ComValsA2iosAmfibianIntfAnAdapter AnAdapter

#endif

#pragma pop_macro("INCLUDE_ALL_ComValsA2iosAmfibianIntfAnAdapter")
