//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../android//com/vals/a2ios/amfibian/intf/AnAdapter.java
//

#ifndef _ComValsA2iosAmfibianIntfAnAdapter_H_
#define _ComValsA2iosAmfibianIntfAnAdapter_H_

#include "J2ObjC_header.h"

@class IOSClass;
@protocol AnAttrib;

@protocol AnAdapter < NSObject, JavaObject >

- (id)convertWithAnAttrib:(id<AnAttrib>)attrib
                   withId:(id)value;

- (void)onWarningWithIOSClass:(IOSClass *)cluss
                 withNSString:(NSString *)attribName
                       withId:(id)value;

@end

J2OBJC_EMPTY_STATIC_INIT(AnAdapter)

J2OBJC_TYPE_LITERAL_HEADER(AnAdapter)

#define ComValsA2iosAmfibianIntfAnAdapter AnAdapter

#endif // _ComValsA2iosAmfibianIntfAnAdapter_H_
