//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../android//com/vals/a2ios/amfibian/intf/AnIncubator.java
//

#ifndef _ComValsA2iosAmfibianIntfAnIncubator_H_
#define _ComValsA2iosAmfibianIntfAnIncubator_H_

#include "J2ObjC_header.h"

@class IOSClass;
@protocol AnAttrib;
@protocol AnOrm;

@protocol AnIncubator < NSObject, JavaObject >

- (void)load__WithNSString:(NSString *)jsonString;

- (void)unload;

- (jboolean)isLoaded;

- (id<AnOrm>)makeWithNSString:(NSString *)name;

- (id<AnOrm>)makeWithIOSClass:(IOSClass *)cluss;

- (IOSClass *)getClassByNameWithNSString:(NSString *)name;

- (NSString *)getAssociationTrgClassNameWithIOSClass:(IOSClass *)cluss
                                        withAnAttrib:(id<AnAttrib>)attrib;

- (NSString *)getAssociationTrgJoinAttribNameWithIOSClass:(IOSClass *)cluss
                                             withAnAttrib:(id<AnAttrib>)attrib;

- (NSString *)getAssociationSrcJoinAttribNameWithIOSClass:(IOSClass *)cluss
                                             withAnAttrib:(id<AnAttrib>)attrib;

- (NSString *)getAssociationSrcAttribNameWithIOSClass:(IOSClass *)cluss
                                         withAnAttrib:(id<AnAttrib>)attrib;

@end

J2OBJC_EMPTY_STATIC_INIT(AnIncubator)

J2OBJC_TYPE_LITERAL_HEADER(AnIncubator)

#define ComValsA2iosAmfibianIntfAnIncubator AnIncubator

#endif // _ComValsA2iosAmfibianIntfAnIncubator_H_
