//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../android//com/vals/a2ios/amfibian/intf/AnObject.java
//

#ifndef _ComValsA2iosAmfibianIntfAnObject_H_
#define _ComValsA2iosAmfibianIntfAnObject_H_

#include "J2ObjC_header.h"

@class IOSClass;
@class IOSObjectArray;
@class OrgJsonJSONArray;
@class OrgJsonJSONObject;
@protocol AnAttrib;
@protocol AnObject_CustomConverter;
@protocol JavaUtilCollection;
@protocol JavaUtilMap;

@protocol AnObject < NSObject, JavaObject >

- (void)resetNativeObject;

- (IOSClass *)getNativeClass;

- (id<JavaUtilMap>)getAllAttribMap;

- (id<AnAttrib>)getAttribWithNSString:(NSString *)attribName;

- (void)addAttribWithAnAttrib:(id<AnAttrib>)anAttrib;

- (id<JavaUtilMap>)asNativeMapWithId:(id)nativeObject;

- (id<JavaUtilMap>)getMapWithId:(id)nativeObject;

- (OrgJsonJSONObject *)asJSONObjectWithId:(id)nativeObject;

- (id)asNativeObjectWithOrgJsonJSONObject:(OrgJsonJSONObject *)jsonObject;

- (id)asNativeObjectWithNSString:(NSString *)jsonString;

- (id<JavaUtilCollection>)asListWithNSString:(NSString *)jsonArrayString;

- (NSString *)asJsonStringWithId:(id)nativeObject;

- (id)getNativeObject;

- (id<JavaUtilMap>)asJsonMap;

- (void)setNativeClassWithIOSClass:(IOSClass *)anObjClass;

- (void)setNativeObjectWithId:(id)o;

- (IOSObjectArray *)getAllAttribs;

- (id<AnObject>)getParentAnObject;

- (IOSObjectArray *)getOwnAttribs;

- (OrgJsonJSONArray *)asJSONArrayWithJavaUtilCollection:(id<JavaUtilCollection>)objects;

- (NSString *)asJsonArrayStringWithJavaUtilCollection:(id<JavaUtilCollection>)objects;

- (id<AnObject_CustomConverter>)getJsonCustomSetConverter;

- (void)setJsonCustomSetConverterWithAnObject_CustomConverter:(id<AnObject_CustomConverter>)objectCustomSetConverter;

- (id<AnObject_CustomConverter>)getJsonCustomGetConverter;

- (void)setJsonCustomGetConverterWithAnObject_CustomConverter:(id<AnObject_CustomConverter>)objectCustomGetConverter;

@end

J2OBJC_EMPTY_STATIC_INIT(AnObject)

J2OBJC_TYPE_LITERAL_HEADER(AnObject)

#define ComValsA2iosAmfibianIntfAnObject AnObject

@protocol AnObject_CustomConverter < NSObject, JavaObject >

- (id)convertWithAnAttrib:(id<AnAttrib>)attrib
                   withId:(id)value;

@end

J2OBJC_EMPTY_STATIC_INIT(AnObject_CustomConverter)

J2OBJC_TYPE_LITERAL_HEADER(AnObject_CustomConverter)

#endif // _ComValsA2iosAmfibianIntfAnObject_H_
