//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../android//com/vals/a2ios/amfibian/intf/AnObject.java
//

#include "J2ObjC_source.h"
#include "com/vals/a2ios/amfibian/intf/AnObject.h"

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(AnObject)
