//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../android//com/vals/a2ios/amfibian/intf/AnObject.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "com/vals/a2ios/amfibian/intf/AnAttrib.h"
#include "com/vals/a2ios/amfibian/intf/AnObject.h"
#include "java/lang/Exception.h"
#include "java/util/Collection.h"
#include "java/util/Map.h"
#include "org/json/JSONArray.h"
#include "org/json/JSONObject.h"

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(AnObject)

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(AnObject_CustomConverter)
