//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../android//com/vals/a2ios/amfibian/intf/AnUpgrade.java
//

#include "J2ObjC_source.h"
#include "com/vals/a2ios/amfibian/intf/AnUpgrade.h"

NSString *AnUpgrade_DB_RECOVER_KEY = @"recoveryKey";
NSString *AnUpgrade_TABLE_NAME = @"app_db_maint";

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(AnUpgrade)
