//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../android//com/vals/a2ios/amfibian/intf/AnUpgrade.java
//

#ifndef _ComValsA2iosAmfibianIntfAnUpgrade_H_
#define _ComValsA2iosAmfibianIntfAnUpgrade_H_

#include "J2ObjC_header.h"

@protocol AnUpgrade < NSObject, JavaObject >

- (void)applyTasks;

@end

J2OBJC_EMPTY_STATIC_INIT(AnUpgrade)

J2OBJC_TYPE_LITERAL_HEADER(AnUpgrade)

#define ComValsA2iosAmfibianIntfAnUpgrade AnUpgrade

#endif // _ComValsA2iosAmfibianIntfAnUpgrade_H_
