//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../android//com/vals/a2ios/amfibian/intf/AnUpgrade.java
//

#ifndef _ComValsA2iosAmfibianIntfAnUpgrade_H_
#define _ComValsA2iosAmfibianIntfAnUpgrade_H_

#include "J2ObjC_header.h"

@protocol JavaUtilList;
@protocol JavaUtilSet;

@protocol AnUpgrade < NSObject, JavaObject >

- (jint)applyUpdates;

- (jint)attemptToRecover;

- (void)setRecoverKeyWithNSString:(NSString *)recoverKey;

- (id<JavaUtilList>)getUpdateKeys;

- (void)setUpdateKeysWithJavaUtilList:(id<JavaUtilList>)updateKey;

- (id<JavaUtilSet>)getAppliedUpdates;

- (id<JavaUtilList>)getTasksByKeyWithNSString:(NSString *)key;

@end

J2OBJC_EMPTY_STATIC_INIT(AnUpgrade)

FOUNDATION_EXPORT NSString *AnUpgrade_DB_RECOVER_KEY_;
J2OBJC_STATIC_FIELD_GETTER(AnUpgrade, DB_RECOVER_KEY_, NSString *)

FOUNDATION_EXPORT NSString *AnUpgrade_TABLE_NAME_;
J2OBJC_STATIC_FIELD_GETTER(AnUpgrade, TABLE_NAME_, NSString *)

J2OBJC_TYPE_LITERAL_HEADER(AnUpgrade)

#define ComValsA2iosAmfibianIntfAnUpgrade AnUpgrade

#endif // _ComValsA2iosAmfibianIntfAnUpgrade_H_
