//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../demo/mobilighter/android/com/vals/a2ios/mobilighter/intf/Mobilighter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComValsA2iosMobilighterIntfMobilighter")
#ifdef RESTRICT_ComValsA2iosMobilighterIntfMobilighter
#define INCLUDE_ALL_ComValsA2iosMobilighterIntfMobilighter 0
#else
#define INCLUDE_ALL_ComValsA2iosMobilighterIntfMobilighter 1
#endif
#undef RESTRICT_ComValsA2iosMobilighterIntfMobilighter

#if !defined (Mobilighter_) && (INCLUDE_ALL_ComValsA2iosMobilighterIntfMobilighter || defined(INCLUDE_Mobilighter))
#define Mobilighter_

@protocol MobilAction;

@protocol Mobilighter < JavaObject >

- (void)setContextWithId:(id)context;

- (id)getContext;

- (void)showOkDialogWithNSString:(NSString *)title
                    withNSString:(NSString *)message;

- (void)showOkDialogWithNSString:(NSString *)title
                    withNSString:(NSString *)message
                 withMobilAction:(id<MobilAction>)okAction;

- (void)showConfirmDialogWithNSString:(NSString *)title
                         withNSString:(NSString *)message
                      withMobilAction:(id<MobilAction>)yesAction
                      withMobilAction:(id<MobilAction>)noAction;

- (void)setPlaceholderWithId:(id)textWidget
                withNSString:(NSString *)text;

- (void)setTextWithId:(id)textWidget
         withNSString:(NSString *)text;

- (NSString *)getTextWithId:(id)textWidget;

- (void)hideWithId:(id)widget;

- (void)showWithId:(id)widget;

- (void)setEnabledWithId:(id)widget
             withBoolean:(jboolean)isEnabled;

- (jboolean)isOnWithId:(id)toggleButton;

- (void)setOnWithId:(id)toggleButton
        withBoolean:(jboolean)isOn;

- (void)addActionListenerWithId:(id)widget
                withMobilAction:(id<MobilAction>)action;

- (NSString *)dateToStringWithId:(id)date
                    withNSString:(NSString *)pattern;

- (void)showWaitPopupWithNSString:(NSString *)title
                     withNSString:(NSString *)message;

- (void)hideWaitPopup;

- (void)setFontWithId:(id)widget
               withId:(id)font
               withId:(id)size;

- (void)setTextColorWithId:(id)widget
                 withFloat:(jfloat)r
                 withFloat:(jfloat)g
                 withFloat:(jfloat)b
                 withFloat:(jfloat)a;

- (void)runOnUiThreadWithMobilAction:(id<MobilAction>)action;

- (NSString *)readFileWithNSString:(NSString *)fileName;

@end

J2OBJC_EMPTY_STATIC_INIT(Mobilighter)

J2OBJC_TYPE_LITERAL_HEADER(Mobilighter)

#define ComValsA2iosMobilighterIntfMobilighter Mobilighter

#endif

#if !defined (Mobilighter_Navigator_) && (INCLUDE_ALL_ComValsA2iosMobilighterIntfMobilighter || defined(INCLUDE_Mobilighter_Navigator))
#define Mobilighter_Navigator_

@protocol Mobilighter_Navigator < JavaObject >

- (void)navigateToScreenWithNSString:(NSString *)name
                              withId:(id)source;

- (void)cleanParameters;

- (void)setStringWithNSString:(NSString *)name
                 withNSString:(NSString *)param;

- (NSString *)getStringWithNSString:(NSString *)name;

- (void)setObjectWithNSString:(NSString *)name
                       withId:(id)param;

- (void)setNumberWithNSString:(NSString *)name
                 withNSNumber:(NSNumber *)param;

- (id)getObjectWithNSString:(NSString *)name;

- (NSNumber *)getNumberWithNSString:(NSString *)name;

- (void)setObjectWithId:(id)param;

- (id)getObject;

@end

J2OBJC_EMPTY_STATIC_INIT(Mobilighter_Navigator)

J2OBJC_TYPE_LITERAL_HEADER(Mobilighter_Navigator)

#endif

#pragma pop_macro("INCLUDE_ALL_ComValsA2iosMobilighterIntfMobilighter")
