//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ..//android/com/vals/a2ios/mobilighter/intf/MobilAction.java
//

#ifndef _ComValsA2iosMobilighterIntfMobilAction_H_
#define _ComValsA2iosMobilighterIntfMobilAction_H_

#include "J2ObjC_header.h"

@protocol MobilAction < NSObject, JavaObject >

- (void)onActionWithId:(id)param;

@end

J2OBJC_EMPTY_STATIC_INIT(MobilAction)

J2OBJC_TYPE_LITERAL_HEADER(MobilAction)

#define ComValsA2iosMobilighterIntfMobilAction MobilAction

#endif // _ComValsA2iosMobilighterIntfMobilAction_H_
