//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ..//android/com/vals/a2ios/mobilighter/intf/Mobilighter.java
//

#include "J2ObjC_source.h"
#include "com/vals/a2ios/mobilighter/intf/MobilAction.h"
#include "com/vals/a2ios/mobilighter/intf/Mobilighter.h"

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(Mobilighter)

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(Mobilighter_Navigator)
