//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../android//com/vals/a2ios/mobilighter/intf/Mobilighter.java
//

#include "J2ObjC_source.h"
#include "com/vals/a2ios/mobilighter/intf/MobilAction.h"
#include "com/vals/a2ios/mobilighter/intf/Mobilighter.h"

NSString *Mobilighter_DATE_FORMAT_STR_ = @"yyyy-MM-dd";
NSString *Mobilighter_DATE_TIME_FORMAT_STR_ = @"yyyy-MM-dd HH:mm:ss";
NSString *Mobilighter_MESSAGE_BOX_ERROR_TITLE_ = @"Oops...";
NSString *Mobilighter_MESSAGE_BOX_OK_BUTTON_ = @"Ok";

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(Mobilighter)
