//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../android//com/vals/a2ios/sqlighter/intf/SQLighterDb.java
//

#include "J2ObjC_source.h"
#include "com/vals/a2ios/sqlighter/intf/SQLighterDb.h"

NSString *SQLighterDb_DATE_HINT = @"_date";
NSString *SQLighterDb_DATE_FORMAT = @"yyyy-MM-dd HH:mm:ss";

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(SQLighterDb)
