//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../android//com/vals/a2ios/sqlighter/intf/SQLighterRs.java
//

#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "com/vals/a2ios/sqlighter/intf/SQLighterRs.h"
#include "java/lang/Double.h"
#include "java/lang/Integer.h"
#include "java/lang/Long.h"
#include "java/util/Date.h"

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(SQLighterRs)
