//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../android//com/vals/a2ios/amfibian/impl/AnIncubatorImpl.java
//

#ifndef _ComValsA2iosAmfibianImplAnIncubatorImpl_H_
#define _ComValsA2iosAmfibianImplAnIncubatorImpl_H_

#include "J2ObjC_header.h"
#include "com/vals/a2ios/amfibian/intf/AnIncubator.h"

@class IOSClass;
@protocol AnOrm;

@interface AnIncubatorImpl : NSObject < AnIncubator >

#pragma mark Public

- (instancetype)init;

- (IOSClass *)getClassByNameWithNSString:(NSString *)name;

- (void)load__WithNSString:(NSString *)jsonString;

- (id<AnOrm>)makeWithIOSClass:(IOSClass *)cluss;

- (id<AnOrm>)makeWithNSString:(NSString *)name;

@end

J2OBJC_EMPTY_STATIC_INIT(AnIncubatorImpl)

FOUNDATION_EXPORT void AnIncubatorImpl_init(AnIncubatorImpl *self);

J2OBJC_TYPE_LITERAL_HEADER(AnIncubatorImpl)

@compatibility_alias ComValsA2iosAmfibianImplAnIncubatorImpl AnIncubatorImpl;

#endif // _ComValsA2iosAmfibianImplAnIncubatorImpl_H_
