//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../android//com/vals/a2ios/amfibian/impl/AnOrm.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "com/vals/a2ios/amfibian/impl/AnAttrib.h"
#include "com/vals/a2ios/amfibian/impl/AnObject.h"
#include "com/vals/a2ios/amfibian/impl/AnOrm.h"
#include "com/vals/a2ios/amfibian/impl/AnSql.h"
#include "com/vals/a2ios/sqlighter/intf/SQLighterDb.h"
#include "com/vals/a2ios/sqlighter/intf/SQLighterRs.h"
#include "java/lang/Exception.h"
#include "java/lang/Long.h"
#include "java/util/Collection.h"
#include "java/util/Iterator.h"
#include "java/util/LinkedList.h"
#include "java/util/List.h"

@interface ComValsA2iosAmfibianImplAnOrm ()

- (void)applyParameters;

@end

__attribute__((unused)) static void ComValsA2iosAmfibianImplAnOrm_applyParameters(ComValsA2iosAmfibianImplAnOrm *self);

@implementation ComValsA2iosAmfibianImplAnOrm

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComValsA2iosAmfibianImplAnOrm_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithSQLighterDb:(id<SQLighterDb>)sqLighterDb
                       withNSString:(NSString *)tableName
                       withIOSClass:(IOSClass *)anObjClass
withComValsA2iosAmfibianImplAnAttribArray:(IOSObjectArray *)attribList
withComValsA2iosAmfibianImplAnObject:(ComValsA2iosAmfibianImplAnObject *)parentAnObject {
  ComValsA2iosAmfibianImplAnOrm_initWithSQLighterDb_withNSString_withIOSClass_withComValsA2iosAmfibianImplAnAttribArray_withComValsA2iosAmfibianImplAnObject_(self, sqLighterDb, tableName, anObjClass, attribList, parentAnObject);
  return self;
}

- (instancetype)initWithSQLighterDb:(id<SQLighterDb>)sqLighterDb
                       withNSString:(NSString *)tableName
                       withIOSClass:(IOSClass *)anObjClass
                  withNSStringArray:(IOSObjectArray *)attribColumnList
withComValsA2iosAmfibianImplAnObject:(ComValsA2iosAmfibianImplAnObject *)parentAnObject {
  ComValsA2iosAmfibianImplAnOrm_initWithSQLighterDb_withNSString_withIOSClass_withNSStringArray_withComValsA2iosAmfibianImplAnObject_(self, sqLighterDb, tableName, anObjClass, attribColumnList, parentAnObject);
  return self;
}

- (id<JavaUtilCollection>)getRecords {
  return [self getRecordsWithJavaUtilCollection:nil];
}

- (id<JavaUtilCollection>)getRecordsWithJavaUtilCollection:(id<JavaUtilCollection>)collectionToUse {
  NSString *queryStr = [self getQueryString];
  if (collectionToUse == nil) {
    collectionToUse = new_JavaUtilLinkedList_init();
  }
  ComValsA2iosAmfibianImplAnOrm_applyParameters(self);
  id<SQLighterRs> rs = [((id<SQLighterDb>) nil_chk(sqlighterDb_)) executeSelectWithNSString:queryStr];
  while ([((id<SQLighterRs>) nil_chk(rs)) hasNext]) {
    [self resetNativeObject];
    jint columnIndex = 0;
    for (NSString * __strong attribName in nil_chk([self getAttribNameList])) {
      if (![self isSkipAttrWithNSString:attribName]) {
        id columnValue = [rs getObjectWithInt:columnIndex++];
        if (columnValue != nil) {
          ComValsA2iosAmfibianImplAnAttrib *ap = [self getAttribWithNSString:attribName];
          [((ComValsA2iosAmfibianImplAnAttrib *) nil_chk(ap)) setValueWithId:columnValue];
        }
      }
    }
    id objectValue = [self getNativeObject];
    id ov = (id) objectValue;
    [((id<JavaUtilCollection>) nil_chk(collectionToUse)) addWithId:ov];
  }
  [rs close];
  return collectionToUse;
}

- (id)getSingleResult {
  id<JavaUtilCollection> l = [self getRecordsWithJavaUtilCollection:nil];
  if (l == nil || [l size] != 1) {
    return nil;
  }
  return [((id<JavaUtilIterator>) nil_chk([((id<JavaUtilCollection>) nil_chk(l)) iterator])) next];
}

- (id)getFirstResultOrNull {
  id<JavaUtilCollection> l = [self getRecordsWithJavaUtilCollection:nil];
  if (l == nil || [l size] == 0) {
    return nil;
  }
  id<JavaUtilIterator> i = [((id<JavaUtilCollection>) nil_chk(l)) iterator];
  return [((id<JavaUtilIterator>) nil_chk(i)) next];
}

- (void)applyParameters {
  ComValsA2iosAmfibianImplAnOrm_applyParameters(self);
}

- (JavaLangLong *)apply {
  if ([self getType] == ComValsA2iosAmfibianImplAnSql_TYPE_INSERT || [self getType] == ComValsA2iosAmfibianImplAnSql_TYPE_UPDATE || [self getType] == ComValsA2iosAmfibianImplAnSql_TYPE_DELETE || [self getType] == ComValsA2iosAmfibianImplAnSql_TYPE_CREATE) {
    NSString *q = [self getQueryString];
    ComValsA2iosAmfibianImplAnOrm_applyParameters(self);
    JavaLangLong *updateInfo = [((id<SQLighterDb>) nil_chk(sqlighterDb_)) executeChangeWithNSString:q];
    return updateInfo;
  }
  return nil;
}

- (void)setSqlighterDbWithSQLighterDb:(id<SQLighterDb>)sqlighterDb {
  self->sqlighterDb_ = sqlighterDb;
}

- (id<SQLighterDb>)getSqlighterDb {
  return sqlighterDb_;
}

@end

void ComValsA2iosAmfibianImplAnOrm_init(ComValsA2iosAmfibianImplAnOrm *self) {
  (void) ComValsA2iosAmfibianImplAnSql_init(self);
}

ComValsA2iosAmfibianImplAnOrm *new_ComValsA2iosAmfibianImplAnOrm_init() {
  ComValsA2iosAmfibianImplAnOrm *self = [ComValsA2iosAmfibianImplAnOrm alloc];
  ComValsA2iosAmfibianImplAnOrm_init(self);
  return self;
}

void ComValsA2iosAmfibianImplAnOrm_initWithSQLighterDb_withNSString_withIOSClass_withComValsA2iosAmfibianImplAnAttribArray_withComValsA2iosAmfibianImplAnObject_(ComValsA2iosAmfibianImplAnOrm *self, id<SQLighterDb> sqLighterDb, NSString *tableName, IOSClass *anObjClass, IOSObjectArray *attribList, ComValsA2iosAmfibianImplAnObject *parentAnObject) {
  (void) ComValsA2iosAmfibianImplAnSql_initWithNSString_withIOSClass_withComValsA2iosAmfibianImplAnAttribArray_withComValsA2iosAmfibianImplAnObject_(self, tableName, anObjClass, attribList, parentAnObject);
  self->sqlighterDb_ = sqLighterDb;
}

ComValsA2iosAmfibianImplAnOrm *new_ComValsA2iosAmfibianImplAnOrm_initWithSQLighterDb_withNSString_withIOSClass_withComValsA2iosAmfibianImplAnAttribArray_withComValsA2iosAmfibianImplAnObject_(id<SQLighterDb> sqLighterDb, NSString *tableName, IOSClass *anObjClass, IOSObjectArray *attribList, ComValsA2iosAmfibianImplAnObject *parentAnObject) {
  ComValsA2iosAmfibianImplAnOrm *self = [ComValsA2iosAmfibianImplAnOrm alloc];
  ComValsA2iosAmfibianImplAnOrm_initWithSQLighterDb_withNSString_withIOSClass_withComValsA2iosAmfibianImplAnAttribArray_withComValsA2iosAmfibianImplAnObject_(self, sqLighterDb, tableName, anObjClass, attribList, parentAnObject);
  return self;
}

void ComValsA2iosAmfibianImplAnOrm_initWithSQLighterDb_withNSString_withIOSClass_withNSStringArray_withComValsA2iosAmfibianImplAnObject_(ComValsA2iosAmfibianImplAnOrm *self, id<SQLighterDb> sqLighterDb, NSString *tableName, IOSClass *anObjClass, IOSObjectArray *attribColumnList, ComValsA2iosAmfibianImplAnObject *parentAnObject) {
  (void) ComValsA2iosAmfibianImplAnSql_initWithNSString_withIOSClass_withNSStringArray_withComValsA2iosAmfibianImplAnObject_(self, tableName, anObjClass, attribColumnList, parentAnObject);
  self->sqlighterDb_ = sqLighterDb;
}

ComValsA2iosAmfibianImplAnOrm *new_ComValsA2iosAmfibianImplAnOrm_initWithSQLighterDb_withNSString_withIOSClass_withNSStringArray_withComValsA2iosAmfibianImplAnObject_(id<SQLighterDb> sqLighterDb, NSString *tableName, IOSClass *anObjClass, IOSObjectArray *attribColumnList, ComValsA2iosAmfibianImplAnObject *parentAnObject) {
  ComValsA2iosAmfibianImplAnOrm *self = [ComValsA2iosAmfibianImplAnOrm alloc];
  ComValsA2iosAmfibianImplAnOrm_initWithSQLighterDb_withNSString_withIOSClass_withNSStringArray_withComValsA2iosAmfibianImplAnObject_(self, sqLighterDb, tableName, anObjClass, attribColumnList, parentAnObject);
  return self;
}

void ComValsA2iosAmfibianImplAnOrm_applyParameters(ComValsA2iosAmfibianImplAnOrm *self) {
  id<JavaUtilList> parameters = [self getParameters];
  for (id __strong par in nil_chk(parameters)) {
    [((id<SQLighterDb>) nil_chk(self->sqlighterDb_)) addParamObjWithId:par];
  }
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComValsA2iosAmfibianImplAnOrm)
