//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../android//com/vals/a2ios/amfibian/impl/AnOrmImpl.java
//

#ifndef _ComValsA2iosAmfibianImplAnOrmImpl_H_
#define _ComValsA2iosAmfibianImplAnOrmImpl_H_

#include "J2ObjC_header.h"
#include "com/vals/a2ios/amfibian/impl/AnSqlImpl.h"
#include "com/vals/a2ios/amfibian/intf/AnOrm.h"

@class IOSClass;
@class IOSObjectArray;
@class JavaLangLong;
@protocol AnObject;
@protocol JavaUtilCollection;
@protocol SQLighterDb;

@interface AnOrmImpl : AnSqlImpl < AnOrm > {
 @public
  id<SQLighterDb> sqlighterDb_;
}

#pragma mark Public

- (instancetype)initWithSQLighterDb:(id<SQLighterDb>)sqLighterDb
                       withNSString:(NSString *)tableName
                       withIOSClass:(IOSClass *)anObjClass
                  withAnAttribArray:(IOSObjectArray *)attribList
                       withAnObject:(id<AnObject>)parentAnObject;

- (instancetype)initWithSQLighterDb:(id<SQLighterDb>)sqLighterDb
                       withNSString:(NSString *)tableName
                       withIOSClass:(IOSClass *)anObjClass
                  withNSStringArray:(IOSObjectArray *)attribColumnList
                       withAnObject:(id<AnObject>)parentAnObject;

- (JavaLangLong *)apply;

- (id)getFirstResultOrNull;

- (id<JavaUtilCollection>)getJSONObjectRecords;

- (id<JavaUtilCollection>)getJSONObjectRecordsWithJavaUtilCollection:(id<JavaUtilCollection>)collectionToUse;

- (id<JavaUtilCollection>)getRecords;

- (id<JavaUtilCollection>)getRecordsWithJavaUtilCollection:(id<JavaUtilCollection>)collectionToUse;

- (id)getSingleResult;

- (id<SQLighterDb>)getSqlighterDb;

- (void)setSqlighterDbWithSQLighterDb:(id<SQLighterDb>)sqlighterDb;

#pragma mark Protected

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(AnOrmImpl)

J2OBJC_FIELD_SETTER(AnOrmImpl, sqlighterDb_, id<SQLighterDb>)

FOUNDATION_EXPORT void AnOrmImpl_init(AnOrmImpl *self);

FOUNDATION_EXPORT AnOrmImpl *new_AnOrmImpl_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void AnOrmImpl_initWithSQLighterDb_withNSString_withIOSClass_withAnAttribArray_withAnObject_(AnOrmImpl *self, id<SQLighterDb> sqLighterDb, NSString *tableName, IOSClass *anObjClass, IOSObjectArray *attribList, id<AnObject> parentAnObject);

FOUNDATION_EXPORT AnOrmImpl *new_AnOrmImpl_initWithSQLighterDb_withNSString_withIOSClass_withAnAttribArray_withAnObject_(id<SQLighterDb> sqLighterDb, NSString *tableName, IOSClass *anObjClass, IOSObjectArray *attribList, id<AnObject> parentAnObject) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void AnOrmImpl_initWithSQLighterDb_withNSString_withIOSClass_withNSStringArray_withAnObject_(AnOrmImpl *self, id<SQLighterDb> sqLighterDb, NSString *tableName, IOSClass *anObjClass, IOSObjectArray *attribColumnList, id<AnObject> parentAnObject);

FOUNDATION_EXPORT AnOrmImpl *new_AnOrmImpl_initWithSQLighterDb_withNSString_withIOSClass_withNSStringArray_withAnObject_(id<SQLighterDb> sqLighterDb, NSString *tableName, IOSClass *anObjClass, IOSObjectArray *attribColumnList, id<AnObject> parentAnObject) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(AnOrmImpl)

@compatibility_alias ComValsA2iosAmfibianImplAnOrmImpl AnOrmImpl;

#endif // _ComValsA2iosAmfibianImplAnOrmImpl_H_
