//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../android//com/vals/a2ios/amfibian/impl/AnUpgrade.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "com/vals/a2ios/amfibian/impl/AnOrm.h"
#include "com/vals/a2ios/amfibian/impl/AnSql.h"
#include "com/vals/a2ios/amfibian/impl/AnUpgrade.h"
#include "com/vals/a2ios/sqlighter/intf/SQLighterDb.h"
#include "com/vals/a2ios/sqlighter/intf/SQLighterRs.h"
#include "java/lang/Exception.h"
#include "java/lang/Long.h"
#include "java/util/HashSet.h"
#include "java/util/List.h"
#include "java/util/Map.h"
#include "java/util/Set.h"

#pragma clang diagnostic ignored "-Wprotocol"
#pragma clang diagnostic ignored "-Wincomplete-implementation"

@interface ComValsA2iosAmfibianImplAnUpgrade () {
 @public
  id<JavaUtilMap> map_;
  id<SQLighterDb> sqlighterDb_;
  ComValsA2iosAmfibianImplAnOrm *ap_;
}

- (void)ensureStorage;

- (id<JavaUtilSet>)getAppliedTasks;

- (void)applyUpdateWithNSString:(NSString *)key
               withJavaUtilList:(id<JavaUtilList>)statementList;

@end

J2OBJC_FIELD_SETTER(ComValsA2iosAmfibianImplAnUpgrade, map_, id<JavaUtilMap>)
J2OBJC_FIELD_SETTER(ComValsA2iosAmfibianImplAnUpgrade, sqlighterDb_, id<SQLighterDb>)
J2OBJC_FIELD_SETTER(ComValsA2iosAmfibianImplAnUpgrade, ap_, ComValsA2iosAmfibianImplAnOrm *)

__attribute__((unused)) static void ComValsA2iosAmfibianImplAnUpgrade_ensureStorage(ComValsA2iosAmfibianImplAnUpgrade *self);

__attribute__((unused)) static id<JavaUtilSet> ComValsA2iosAmfibianImplAnUpgrade_getAppliedTasks(ComValsA2iosAmfibianImplAnUpgrade *self);

__attribute__((unused)) static void ComValsA2iosAmfibianImplAnUpgrade_applyUpdateWithNSString_withJavaUtilList_(ComValsA2iosAmfibianImplAnUpgrade *self, NSString *key, id<JavaUtilList> statementList);

@interface ComValsA2iosAmfibianImplAnUpgrade_Upgrade () {
 @public
  NSString *key_;
  NSString *value_;
}

@end

J2OBJC_FIELD_SETTER(ComValsA2iosAmfibianImplAnUpgrade_Upgrade, key_, NSString *)
J2OBJC_FIELD_SETTER(ComValsA2iosAmfibianImplAnUpgrade_Upgrade, value_, NSString *)

@implementation ComValsA2iosAmfibianImplAnUpgrade

- (instancetype)initWithSQLighterDb:(id<SQLighterDb>)sqLighterDb {
  ComValsA2iosAmfibianImplAnUpgrade_initWithSQLighterDb_(self, sqLighterDb);
  return self;
}

- (NSString *)getTableName {
  return ComValsA2iosAmfibianImplAnUpgrade_Upgrade_TABLE_;
}

- (void)ensureStorage {
  ComValsA2iosAmfibianImplAnUpgrade_ensureStorage(self);
}

- (id<JavaUtilSet>)getAppliedTasks {
  return ComValsA2iosAmfibianImplAnUpgrade_getAppliedTasks(self);
}

- (void)applyTasks {
  id<JavaUtilSet> appliedKeys = ComValsA2iosAmfibianImplAnUpgrade_getAppliedTasks(self);
  for (NSString * __strong updKey in nil_chk([self getAllKeys])) {
    if (![((id<JavaUtilSet>) nil_chk(appliedKeys)) containsWithId:updKey]) {
      ComValsA2iosAmfibianImplAnUpgrade_applyUpdateWithNSString_withJavaUtilList_(self, updKey, [self getTaskByKeyWithNSString:updKey]);
    }
  }
}

- (void)applyUpdateWithNSString:(NSString *)key
               withJavaUtilList:(id<JavaUtilList>)statementList {
  ComValsA2iosAmfibianImplAnUpgrade_applyUpdateWithNSString_withJavaUtilList_(self, key, statementList);
}

@end

void ComValsA2iosAmfibianImplAnUpgrade_initWithSQLighterDb_(ComValsA2iosAmfibianImplAnUpgrade *self, id<SQLighterDb> sqLighterDb) {
  (void) NSObject_init(self);
  self->sqlighterDb_ = sqLighterDb;
  self->ap_ = new_ComValsA2iosAmfibianImplAnOrm_initWithSQLighterDb_withNSString_withIOSClass_withNSStringArray_withComValsA2iosAmfibianImplAnObject_(sqLighterDb, [self getTableName], ComValsA2iosAmfibianImplAnUpgrade_Upgrade_class_(), [IOSObjectArray newArrayWithObjects:(id[]){ @"key", @"value" } count:2 type:NSString_class_()], nil);
  ComValsA2iosAmfibianImplAnUpgrade_ensureStorage(self);
}

void ComValsA2iosAmfibianImplAnUpgrade_ensureStorage(ComValsA2iosAmfibianImplAnUpgrade *self) {
  id<SQLighterRs> rs = [((id<SQLighterDb>) nil_chk(self->sqlighterDb_)) executeSelectWithNSString:@"SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"];
  jboolean isFound = false;
  while ([((id<SQLighterRs>) nil_chk(rs)) hasNext]) {
    NSString *tableName = [rs getStringWithInt:0];
    if ([((NSString *) nil_chk(tableName)) isEqual:[self getTableName]]) {
      isFound = true;
      break;
    }
  }
  [rs close];
  if (!isFound) {
    NSString *createSql = [((ComValsA2iosAmfibianImplAnSql *) nil_chk([((ComValsA2iosAmfibianImplAnOrm *) nil_chk(self->ap_)) startSqlCreate])) getQueryString];
    (void) [self->sqlighterDb_ executeChangeWithNSString:createSql];
  }
}

id<JavaUtilSet> ComValsA2iosAmfibianImplAnUpgrade_getAppliedTasks(ComValsA2iosAmfibianImplAnUpgrade *self) {
  id<JavaUtilSet> keys = new_JavaUtilHashSet_init();
  id<SQLighterRs> rs = [((id<SQLighterDb>) nil_chk(self->sqlighterDb_)) executeSelectWithNSString:JreStrcat("$$$", @"select key from ", ComValsA2iosAmfibianImplAnUpgrade_Upgrade_TABLE_, @" where value is not null")];
  while ([((id<SQLighterRs>) nil_chk(rs)) hasNext]) {
    NSString *key = [rs getStringWithInt:0];
    [keys addWithId:key];
  }
  [rs close];
  return keys;
}

void ComValsA2iosAmfibianImplAnUpgrade_applyUpdateWithNSString_withJavaUtilList_(ComValsA2iosAmfibianImplAnUpgrade *self, NSString *key, id<JavaUtilList> statementList) {
  [((id<SQLighterDb>) nil_chk(self->sqlighterDb_)) beginTransaction];
  for (id __strong task in nil_chk(statementList)) {
    NSString *sqlStr = nil;
    if ([task isKindOfClass:[NSString class]]) {
      sqlStr = (NSString *) check_class_cast(task, [NSString class]);
      (void) [self->sqlighterDb_ executeChangeWithNSString:sqlStr];
    }
    else if ([task isKindOfClass:[ComValsA2iosAmfibianImplAnSql class]]) {
      ComValsA2iosAmfibianImplAnOrm *sql = (ComValsA2iosAmfibianImplAnOrm *) check_class_cast(task, [ComValsA2iosAmfibianImplAnOrm class]);
      [((ComValsA2iosAmfibianImplAnOrm *) nil_chk(sql)) setSqlighterDbWithSQLighterDb:self->sqlighterDb_];
      (void) [sql startSqlCreate];
      sqlStr = [sql getQueryString];
      (void) [self->sqlighterDb_ executeChangeWithNSString:sqlStr];
    }
    ComValsA2iosAmfibianImplAnUpgrade_Upgrade *appUpdate = new_ComValsA2iosAmfibianImplAnUpgrade_Upgrade_init();
    [appUpdate setKeyWithNSString:key];
    [appUpdate setValueWithNSString:sqlStr];
    [((ComValsA2iosAmfibianImplAnOrm *) nil_chk(self->ap_)) startSqlInsertWithId:appUpdate];
    (void) [self->ap_ apply];
  }
  ComValsA2iosAmfibianImplAnUpgrade_Upgrade *appUpdateMark = new_ComValsA2iosAmfibianImplAnUpgrade_Upgrade_init();
  [appUpdateMark setKeyWithNSString:key];
  [((ComValsA2iosAmfibianImplAnOrm *) nil_chk(self->ap_)) startSqlInsertWithId:appUpdateMark];
  (void) [self->ap_ apply];
  [self->sqlighterDb_ commitTransaction];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComValsA2iosAmfibianImplAnUpgrade)

NSString *ComValsA2iosAmfibianImplAnUpgrade_Upgrade_TABLE_ = @"app_db_maint";

@implementation ComValsA2iosAmfibianImplAnUpgrade_Upgrade

- (NSString *)getKey {
  return key_;
}

- (void)setKeyWithNSString:(NSString *)key {
  self->key_ = key;
}

- (NSString *)getValue {
  return value_;
}

- (void)setValueWithNSString:(NSString *)value {
  self->value_ = value;
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComValsA2iosAmfibianImplAnUpgrade_Upgrade_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

@end

void ComValsA2iosAmfibianImplAnUpgrade_Upgrade_init(ComValsA2iosAmfibianImplAnUpgrade_Upgrade *self) {
  (void) NSObject_init(self);
}

ComValsA2iosAmfibianImplAnUpgrade_Upgrade *new_ComValsA2iosAmfibianImplAnUpgrade_Upgrade_init() {
  ComValsA2iosAmfibianImplAnUpgrade_Upgrade *self = [ComValsA2iosAmfibianImplAnUpgrade_Upgrade alloc];
  ComValsA2iosAmfibianImplAnUpgrade_Upgrade_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComValsA2iosAmfibianImplAnUpgrade_Upgrade)
