//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../android//com/vals/a2ios/amfibian/impl/AnUpgradeImpl.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "com/vals/a2ios/amfibian/impl/AnOrmImpl.h"
#include "com/vals/a2ios/amfibian/impl/AnUpgradeImpl.h"
#include "com/vals/a2ios/amfibian/intf/AnSql.h"
#include "com/vals/a2ios/amfibian/intf/AnUpgrade.h"
#include "com/vals/a2ios/sqlighter/intf/SQLighterDb.h"
#include "com/vals/a2ios/sqlighter/intf/SQLighterRs.h"
#include "java/io/PrintStream.h"
#include "java/lang/Double.h"
#include "java/lang/Integer.h"
#include "java/lang/Long.h"
#include "java/lang/System.h"
#include "java/lang/Throwable.h"
#include "java/util/Arrays.h"
#include "java/util/Date.h"
#include "java/util/HashSet.h"
#include "java/util/LinkedList.h"
#include "java/util/List.h"
#include "java/util/Map.h"
#include "java/util/Set.h"

#pragma clang diagnostic ignored "-Wprotocol"

@interface AnUpgradeImpl () {
 @public
  id<JavaUtilMap> map_;
  NSString *recoverKey_;
  NSString *logTableName_;
  id<JavaUtilList> delayedLogs_;
}

- (jint)applyUpdatesWithInt:(jint)privatePublic;

- (jint)attemptToRecoverWithInt:(jint)privatePublic;

- (void)logUpgradeStepWithNSString:(NSString *)key
                      withNSString:(NSString *)sqlStr
                  withJavaLangLong:(JavaLangLong *)result;

- (void)logKeyWithNSString:(NSString *)key
              withNSString:(NSString *)message
       withJavaLangInteger:(JavaLangInteger *)status;

- (void)saveLogWithAnUpgradeImpl_Upgrade:(AnUpgradeImpl_Upgrade *)appUpdateEntry;

- (jboolean)findTableWithNSString:(NSString *)searchTableName;

- (id<JavaUtilList>)getPrivateUpdateKeys;

@end

J2OBJC_FIELD_SETTER(AnUpgradeImpl, map_, id<JavaUtilMap>)
J2OBJC_FIELD_SETTER(AnUpgradeImpl, recoverKey_, NSString *)
J2OBJC_FIELD_SETTER(AnUpgradeImpl, logTableName_, NSString *)
J2OBJC_FIELD_SETTER(AnUpgradeImpl, delayedLogs_, id<JavaUtilList>)

inline NSString *AnUpgradeImpl_get_PRIVATE_PREFIX();
static NSString *AnUpgradeImpl_PRIVATE_PREFIX = @"an-upg-";
J2OBJC_STATIC_FIELD_OBJ_FINAL(AnUpgradeImpl, PRIVATE_PREFIX, NSString *)

inline NSString *AnUpgradeImpl_get_PRIVATE_REC_KEY();
static NSString *AnUpgradeImpl_PRIVATE_REC_KEY = @"an-upg-recoveryKey";
J2OBJC_STATIC_FIELD_OBJ_FINAL(AnUpgradeImpl, PRIVATE_REC_KEY, NSString *)

inline NSString *AnUpgradeImpl_get_PRIVATE_KEY1();
static NSString *AnUpgradeImpl_PRIVATE_KEY1 = @"an-upg-init-1";
J2OBJC_STATIC_FIELD_OBJ_FINAL(AnUpgradeImpl, PRIVATE_KEY1, NSString *)

__attribute__((unused)) static jint AnUpgradeImpl_applyUpdatesWithInt_(AnUpgradeImpl *self, jint privatePublic);

__attribute__((unused)) static jint AnUpgradeImpl_attemptToRecoverWithInt_(AnUpgradeImpl *self, jint privatePublic);

__attribute__((unused)) static void AnUpgradeImpl_logUpgradeStepWithNSString_withNSString_withJavaLangLong_(AnUpgradeImpl *self, NSString *key, NSString *sqlStr, JavaLangLong *result);

__attribute__((unused)) static void AnUpgradeImpl_logKeyWithNSString_withNSString_withJavaLangInteger_(AnUpgradeImpl *self, NSString *key, NSString *message, JavaLangInteger *status);

__attribute__((unused)) static void AnUpgradeImpl_saveLogWithAnUpgradeImpl_Upgrade_(AnUpgradeImpl *self, AnUpgradeImpl_Upgrade *appUpdateEntry);

__attribute__((unused)) static jboolean AnUpgradeImpl_findTableWithNSString_(AnUpgradeImpl *self, NSString *searchTableName);

__attribute__((unused)) static id<JavaUtilList> AnUpgradeImpl_getPrivateUpdateKeys(AnUpgradeImpl *self);

@interface AnUpgradeImpl_Upgrade () {
 @public
  NSString *key_;
  NSString *value_;
  JavaUtilDate *createDate_;
  JavaLangInteger *status_;
  JavaLangInteger *type_;
  JavaLangInteger *refi_;
  JavaLangDouble *refd_;
  JavaLangInteger *refs_;
}

@end

J2OBJC_FIELD_SETTER(AnUpgradeImpl_Upgrade, key_, NSString *)
J2OBJC_FIELD_SETTER(AnUpgradeImpl_Upgrade, value_, NSString *)
J2OBJC_FIELD_SETTER(AnUpgradeImpl_Upgrade, createDate_, JavaUtilDate *)
J2OBJC_FIELD_SETTER(AnUpgradeImpl_Upgrade, status_, JavaLangInteger *)
J2OBJC_FIELD_SETTER(AnUpgradeImpl_Upgrade, type_, JavaLangInteger *)
J2OBJC_FIELD_SETTER(AnUpgradeImpl_Upgrade, refi_, JavaLangInteger *)
J2OBJC_FIELD_SETTER(AnUpgradeImpl_Upgrade, refd_, JavaLangDouble *)
J2OBJC_FIELD_SETTER(AnUpgradeImpl_Upgrade, refs_, JavaLangInteger *)

@implementation AnUpgradeImpl

- (instancetype)initWithSQLighterDb:(id<SQLighterDb>)sqLighterDb
                       withNSString:(NSString *)tableName
                       withNSString:(NSString *)recoveryKey {
  AnUpgradeImpl_initWithSQLighterDb_withNSString_withNSString_(self, sqLighterDb, tableName, recoveryKey);
  return self;
}

- (instancetype)initWithSQLighterDb:(id<SQLighterDb>)sqLighterDb {
  AnUpgradeImpl_initWithSQLighterDb_(self, sqLighterDb);
  return self;
}

- (id<JavaUtilList>)getTasksByKeyWithNSString:(NSString *)key {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<JavaUtilList>)getUpdateKeys {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (NSString *)getLogTableName {
  return logTableName_;
}

- (void)setLogTableNameWithNSString:(NSString *)logTableName {
  self->logTableName_ = logTableName;
}

- (id<JavaUtilSet>)getAppliedUpdates {
  id<JavaUtilSet> keys = new_JavaUtilHashSet_init();
  if (!AnUpgradeImpl_findTableWithNSString_(self, [self getLogTableName])) {
    return keys;
  }
  id<SQLighterRs> rs = [((id<SQLighterDb>) nil_chk(sqlighterDb_)) executeSelectWithNSString:JreStrcat("$$$", @"select key from ", AnUpgrade_TABLE_NAME, @" where type = 0")];
  while ([((id<SQLighterRs>) nil_chk(rs)) hasNext]) {
    NSString *key = [rs getStringWithInt:0];
    [keys addWithId:key];
  }
  [rs close];
  return keys;
}

- (jint)applyUpdates {
  if (!AnUpgradeImpl_findTableWithNSString_(self, [self getLogTableName])) {
    jint returnCode = AnUpgradeImpl_attemptToRecoverWithInt_(self, 0);
    if (returnCode == -1) {
      return returnCode;
    }
  }
  jint taskCount = AnUpgradeImpl_applyUpdatesWithInt_(self, 0);
  if (taskCount == -1) {
    return taskCount;
  }
  taskCount = AnUpgradeImpl_applyUpdatesWithInt_(self, 1);
  return taskCount;
}

- (jint)applyUpdatesWithInt:(jint)privatePublic {
  return AnUpgradeImpl_applyUpdatesWithInt_(self, privatePublic);
}

- (jboolean)applyUpdateWithNSString:(NSString *)key
                   withJavaUtilList:(id<JavaUtilList>)statementList {
  id taskObject = nil;
  @try {
    for (id __strong task in nil_chk(statementList)) {
      taskObject = task;
      NSString *sqlStr = nil;
      JavaLangLong *result = nil;
      if ([task isKindOfClass:[NSString class]]) {
        sqlStr = (NSString *) cast_chk(task, [NSString class]);
        result = [((id<SQLighterDb>) nil_chk(sqlighterDb_)) executeChangeWithNSString:sqlStr];
      }
      else if ([task isKindOfClass:[AnOrmImpl class]]) {
        AnOrmImpl *createObjectTask = (AnOrmImpl *) cast_chk(task, [AnOrmImpl class]);
        [((AnOrmImpl *) nil_chk(createObjectTask)) setSqlighterDbWithSQLighterDb:sqlighterDb_];
        (void) [createObjectTask startSqlCreate];
        sqlStr = [createObjectTask getQueryString];
        NSString *dropTableQuery = JreStrcat("$$", @"drop table if exists ", [createObjectTask getTableName]);
        (void) [((id<SQLighterDb>) nil_chk(sqlighterDb_)) executeChangeWithNSString:dropTableQuery];
        result = [createObjectTask apply];
      }
      [self onTaskSuccessWithId:task];
      AnUpgradeImpl_logUpgradeStepWithNSString_withNSString_withJavaLangLong_(self, key, sqlStr, result);
    }
    AnUpgradeImpl_logKeyWithNSString_withNSString_withJavaLangInteger_(self, key, nil, JavaLangInteger_valueOfWithInt_(1));
    return true;
  }
  @catch (JavaLangThrowable *t) {
    [self onTaskFailWithId:taskObject withJavaLangThrowable:t];
    @try {
      AnUpgradeImpl_logKeyWithNSString_withNSString_withJavaLangInteger_(self, key, [t getMessage], JavaLangInteger_valueOfWithInt_(0));
    }
    @catch (JavaLangThrowable *failureMarkExcp) {
      [failureMarkExcp printStackTrace];
    }
    return false;
  }
}

- (jint)attemptToRecover {
  jint returnCode = AnUpgradeImpl_attemptToRecoverWithInt_(self, 0);
  if (returnCode == -1) {
    return returnCode;
  }
  returnCode = AnUpgradeImpl_attemptToRecoverWithInt_(self, 1);
  return returnCode;
}

- (jint)attemptToRecoverWithInt:(jint)privatePublic {
  return AnUpgradeImpl_attemptToRecoverWithInt_(self, privatePublic);
}

- (void)setRecoverKeyWithNSString:(NSString *)recoverKey {
  self->recoverKey_ = recoverKey;
}

- (void)logUpgradeStepWithNSString:(NSString *)key
                      withNSString:(NSString *)sqlStr
                  withJavaLangLong:(JavaLangLong *)result {
  AnUpgradeImpl_logUpgradeStepWithNSString_withNSString_withJavaLangLong_(self, key, sqlStr, result);
}

- (void)logKeyWithNSString:(NSString *)key
              withNSString:(NSString *)message
       withJavaLangInteger:(JavaLangInteger *)status {
  AnUpgradeImpl_logKeyWithNSString_withNSString_withJavaLangInteger_(self, key, message, status);
}

- (void)saveLogWithAnUpgradeImpl_Upgrade:(AnUpgradeImpl_Upgrade *)appUpdateEntry {
  AnUpgradeImpl_saveLogWithAnUpgradeImpl_Upgrade_(self, appUpdateEntry);
}

- (jboolean)findTableWithNSString:(NSString *)searchTableName {
  return AnUpgradeImpl_findTableWithNSString_(self, searchTableName);
}

- (void)onTaskSuccessWithId:(id)task {
}

- (void)onTaskFailWithId:(id)task
   withJavaLangThrowable:(JavaLangThrowable *)exception {
}

- (id<JavaUtilList>)getPrivateUpdateKeys {
  return AnUpgradeImpl_getPrivateUpdateKeys(self);
}

- (id<JavaUtilList>)getPrivateTasksByKeyWithNSString:(NSString *)key {
  id<JavaUtilList> tasks = new_JavaUtilLinkedList_init();
  if ([((NSString *) nil_chk(AnUpgradeImpl_PRIVATE_REC_KEY)) isEqual:key]) {
    [tasks addWithId:anOrm_];
    [tasks addWithId:JreStrcat("$$$$$", @"create index ", [self getLogTableName], @"_idx on ", [self getLogTableName], @"(key, type, status)")];
  }
  else if ([((NSString *) nil_chk(AnUpgradeImpl_PRIVATE_KEY1)) isEqual:key]) {
    [tasks addWithId:JreStrcat("$$$", @"alter table ", [self getLogTableName], @" add column type INTEGER")];
    [tasks addWithId:JreStrcat("$$$", @"alter table ", [self getLogTableName], @" add column refi INTEGER")];
    [tasks addWithId:JreStrcat("$$$", @"alter table ", [self getLogTableName], @" add column refd REAL")];
    [tasks addWithId:JreStrcat("$$$", @"alter table ", [self getLogTableName], @" add column refs TEXT")];
    [tasks addWithId:JreStrcat("$$$$$", @"create index ", [self getLogTableName], @"_idx on ", [self getLogTableName], @"(key, type, status)")];
    [tasks addWithId:JreStrcat("$$$", @"update ", [self getLogTableName], @" set type = 0 where value is null")];
    [tasks addWithId:JreStrcat("$$$", @"update ", [self getLogTableName], @" set type = 1 where value is not null")];
  }
  return tasks;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, 1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 2, 1, -1, -1, -1 },
    { NULL, "LJavaUtilList;", 0x401, 3, 4, -1, 5, -1, -1 },
    { NULL, "LJavaUtilList;", 0x401, -1, -1, -1, 6, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 7, 4, -1, -1, -1, -1 },
    { NULL, "LJavaUtilSet;", 0x1, -1, -1, 1, 8, -1, -1 },
    { NULL, "I", 0x1, -1, -1, 1, -1, -1, -1 },
    { NULL, "I", 0x2, 9, 10, 1, -1, -1, -1 },
    { NULL, "Z", 0x4, 11, 12, -1, 13, -1, -1 },
    { NULL, "I", 0x1, -1, -1, 1, -1, -1, -1 },
    { NULL, "I", 0x2, 14, 10, 1, -1, -1, -1 },
    { NULL, "V", 0x1, 15, 4, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 16, 17, 1, -1, -1, -1 },
    { NULL, "V", 0x2, 18, 19, 1, -1, -1, -1 },
    { NULL, "V", 0x2, 20, 21, 1, -1, -1, -1 },
    { NULL, "Z", 0x2, 22, 4, 1, -1, -1, -1 },
    { NULL, "V", 0x1, 23, 24, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 25, 26, -1, -1, -1, -1 },
    { NULL, "LJavaUtilList;", 0x2, -1, -1, -1, 6, -1, -1 },
    { NULL, "LJavaUtilList;", 0x4, 27, 4, -1, 5, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithSQLighterDb:withNSString:withNSString:);
  methods[1].selector = @selector(initWithSQLighterDb:);
  methods[2].selector = @selector(getTasksByKeyWithNSString:);
  methods[3].selector = @selector(getUpdateKeys);
  methods[4].selector = @selector(getLogTableName);
  methods[5].selector = @selector(setLogTableNameWithNSString:);
  methods[6].selector = @selector(getAppliedUpdates);
  methods[7].selector = @selector(applyUpdates);
  methods[8].selector = @selector(applyUpdatesWithInt:);
  methods[9].selector = @selector(applyUpdateWithNSString:withJavaUtilList:);
  methods[10].selector = @selector(attemptToRecover);
  methods[11].selector = @selector(attemptToRecoverWithInt:);
  methods[12].selector = @selector(setRecoverKeyWithNSString:);
  methods[13].selector = @selector(logUpgradeStepWithNSString:withNSString:withJavaLangLong:);
  methods[14].selector = @selector(logKeyWithNSString:withNSString:withJavaLangInteger:);
  methods[15].selector = @selector(saveLogWithAnUpgradeImpl_Upgrade:);
  methods[16].selector = @selector(findTableWithNSString:);
  methods[17].selector = @selector(onTaskSuccessWithId:);
  methods[18].selector = @selector(onTaskFailWithId:withJavaLangThrowable:);
  methods[19].selector = @selector(getPrivateUpdateKeys);
  methods[20].selector = @selector(getPrivateTasksByKeyWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "map_", "LJavaUtilMap;", .constantValue.asLong = 0, 0x2, -1, -1, 28, -1 },
    { "sqlighterDb_", "LSQLighterDb;", .constantValue.asLong = 0, 0x4, -1, -1, -1, -1 },
    { "recoverKey_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "logTableName_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "anOrm_", "LAnOrmImpl;", .constantValue.asLong = 0, 0x4, -1, -1, 29, -1 },
    { "delayedLogs_", "LJavaUtilList;", .constantValue.asLong = 0, 0x2, -1, -1, 30, -1 },
    { "PRIVATE_PREFIX", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 31, -1, -1 },
    { "PRIVATE_REC_KEY", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 32, -1, -1 },
    { "PRIVATE_KEY1", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 33, -1, -1 },
  };
  static const void *ptrTable[] = { "LSQLighterDb;LNSString;LNSString;", "LJavaLangException;", "LSQLighterDb;", "getTasksByKey", "LNSString;", "(Ljava/lang/String;)Ljava/util/List<Ljava/lang/Object;>;", "()Ljava/util/List<Ljava/lang/String;>;", "setLogTableName", "()Ljava/util/Set<Ljava/lang/String;>;", "applyUpdates", "I", "applyUpdate", "LNSString;LJavaUtilList;", "(Ljava/lang/String;Ljava/util/List<Ljava/lang/Object;>;)Z", "attemptToRecover", "setRecoverKey", "logUpgradeStep", "LNSString;LNSString;LJavaLangLong;", "logKey", "LNSString;LNSString;LJavaLangInteger;", "saveLog", "LAnUpgradeImpl_Upgrade;", "findTable", "onTaskSuccess", "LNSObject;", "onTaskFail", "LNSObject;LJavaLangThrowable;", "getPrivateTasksByKey", "Ljava/util/Map<Ljava/lang/Integer;Ljava/util/List<Ljava/lang/String;>;>;", "Lcom/vals/a2ios/amfibian/impl/AnOrmImpl<Lcom/vals/a2ios/amfibian/impl/AnUpgradeImpl$Upgrade;>;", "Ljava/util/List<Lcom/vals/a2ios/amfibian/impl/AnUpgradeImpl$Upgrade;>;", &AnUpgradeImpl_PRIVATE_PREFIX, &AnUpgradeImpl_PRIVATE_REC_KEY, &AnUpgradeImpl_PRIVATE_KEY1 };
  static const J2ObjcClassInfo _AnUpgradeImpl = { "AnUpgradeImpl", "com.vals.a2ios.amfibian.impl", ptrTable, methods, fields, 7, 0x401, 21, 9, -1, 21, -1, -1, -1 };
  return &_AnUpgradeImpl;
}

@end

void AnUpgradeImpl_initWithSQLighterDb_withNSString_withNSString_(AnUpgradeImpl *self, id<SQLighterDb> sqLighterDb, NSString *tableName, NSString *recoveryKey) {
  AnUpgradeImpl_initWithSQLighterDb_(self, sqLighterDb);
  self->logTableName_ = tableName;
  self->recoverKey_ = recoveryKey;
}

void AnUpgradeImpl_initWithSQLighterDb_(AnUpgradeImpl *self, id<SQLighterDb> sqLighterDb) {
  NSObject_init(self);
  self->recoverKey_ = AnUpgrade_DB_RECOVER_KEY;
  self->logTableName_ = AnUpgrade_TABLE_NAME;
  self->delayedLogs_ = new_JavaUtilLinkedList_init();
  self->sqlighterDb_ = sqLighterDb;
  self->anOrm_ = new_AnOrmImpl_initWithSQLighterDb_withNSString_withIOSClass_withNSStringArray_withAnObject_(sqLighterDb, [self getLogTableName], AnUpgradeImpl_Upgrade_class_(), [IOSObjectArray newArrayWithObjects:(id[]){ @"key", @"value", @"createDate,create_date", @"status", @"type", @"refi", @"refd", @"refs" } count:8 type:NSString_class_()], nil);
}

jint AnUpgradeImpl_applyUpdatesWithInt_(AnUpgradeImpl *self, jint privatePublic) {
  jint taskCount = 0;
  id<JavaUtilSet> appliedKeys = [self getAppliedUpdates];
  id<JavaUtilList> keys = (privatePublic == 0) ? AnUpgradeImpl_getPrivateUpdateKeys(self) : [self getUpdateKeys];
  for (NSString * __strong updKey in keys) {
    if ([((NSString *) nil_chk(updKey)) isEqual:self->recoverKey_]) {
      continue;
    }
    if (![((id<JavaUtilSet>) nil_chk(appliedKeys)) containsWithId:updKey]) {
      id<JavaUtilList> tasks = (privatePublic == 0) ? [self getPrivateTasksByKeyWithNSString:updKey] : [self getTasksByKeyWithNSString:updKey];
      if (![self applyUpdateWithNSString:updKey withJavaUtilList:tasks]) {
        return -1;
      }
      taskCount++;
    }
  }
  return taskCount;
}

jint AnUpgradeImpl_attemptToRecoverWithInt_(AnUpgradeImpl *self, jint privatePublic) {
  id<JavaUtilList> recoverTasks = (privatePublic == 0) ? [self getPrivateTasksByKeyWithNSString:AnUpgradeImpl_PRIVATE_REC_KEY] : [self getTasksByKeyWithNSString:self->recoverKey_];
  jint rc = 0;
  if ([recoverTasks size] > 0) {
    id<JavaUtilList> keys = (privatePublic == 0) ? AnUpgradeImpl_getPrivateUpdateKeys(self) : [self getUpdateKeys];
    for (NSString * __strong key in keys) {
      NSString *recKey = (privatePublic == 0) ? AnUpgradeImpl_PRIVATE_REC_KEY : self->recoverKey_;
      if ([((NSString *) nil_chk(key)) isEqual:recKey]) {
        jboolean result = [self applyUpdateWithNSString:key withJavaUtilList:recoverTasks];
        if (!result) {
          return -1;
        }
        rc++;
      }
      if (![key isEqual:self->recoverKey_]) {
        AnUpgradeImpl_logKeyWithNSString_withNSString_withJavaLangInteger_(self, key, nil, JavaLangInteger_valueOfWithInt_(0));
      }
    }
  }
  return rc;
}

void AnUpgradeImpl_logUpgradeStepWithNSString_withNSString_withJavaLangLong_(AnUpgradeImpl *self, NSString *key, NSString *sqlStr, JavaLangLong *result) {
  [((JavaIoPrintStream *) nil_chk(JreLoadStatic(JavaLangSystem, out))) printlnWithNSString:JreStrcat("$@$$", @"result: ", result, @" for ", sqlStr)];
  AnUpgradeImpl_Upgrade *appUpdate = new_AnUpgradeImpl_Upgrade_init();
  [appUpdate setKeyWithNSString:key];
  [appUpdate setValueWithNSString:sqlStr];
  [appUpdate setCreateDateWithJavaUtilDate:new_JavaUtilDate_init()];
  [appUpdate setStatusWithJavaLangInteger:JavaLangInteger_valueOfWithInt_(1)];
  [appUpdate setTypeWithJavaLangInteger:JavaLangInteger_valueOfWithInt_(1)];
  AnUpgradeImpl_saveLogWithAnUpgradeImpl_Upgrade_(self, appUpdate);
}

void AnUpgradeImpl_logKeyWithNSString_withNSString_withJavaLangInteger_(AnUpgradeImpl *self, NSString *key, NSString *message, JavaLangInteger *status) {
  AnUpgradeImpl_Upgrade *appUpdateMark = new_AnUpgradeImpl_Upgrade_init();
  [appUpdateMark setKeyWithNSString:key];
  [appUpdateMark setStatusWithJavaLangInteger:status];
  [appUpdateMark setCreateDateWithJavaUtilDate:new_JavaUtilDate_init()];
  [appUpdateMark setTypeWithJavaLangInteger:JavaLangInteger_valueOfWithInt_(0)];
  if (message != nil) {
    [appUpdateMark setValueWithNSString:message];
  }
  AnUpgradeImpl_saveLogWithAnUpgradeImpl_Upgrade_(self, appUpdateMark);
}

void AnUpgradeImpl_saveLogWithAnUpgradeImpl_Upgrade_(AnUpgradeImpl *self, AnUpgradeImpl_Upgrade *appUpdateEntry) {
  if (!AnUpgradeImpl_findTableWithNSString_(self, [self getLogTableName])) {
    [((id<JavaUtilList>) nil_chk(self->delayedLogs_)) addWithId:appUpdateEntry];
  }
  else {
    for (AnUpgradeImpl_Upgrade * __strong upgradeLog in nil_chk(self->delayedLogs_)) {
      [((AnOrmImpl *) nil_chk(self->anOrm_)) startSqlInsertWithId:upgradeLog];
      (void) [((AnOrmImpl *) nil_chk(self->anOrm_)) apply];
    }
    [self->delayedLogs_ clear];
    [((AnOrmImpl *) nil_chk(self->anOrm_)) startSqlInsertWithId:appUpdateEntry];
    (void) [((AnOrmImpl *) nil_chk(self->anOrm_)) apply];
  }
}

jboolean AnUpgradeImpl_findTableWithNSString_(AnUpgradeImpl *self, NSString *searchTableName) {
  id<SQLighterRs> rs = [((id<SQLighterDb>) nil_chk(self->sqlighterDb_)) executeSelectWithNSString:@"SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"];
  jboolean isFound = false;
  while ([((id<SQLighterRs>) nil_chk(rs)) hasNext]) {
    NSString *tableName = [rs getStringWithInt:0];
    if ([((NSString *) nil_chk(tableName)) isEqual:[self getLogTableName]]) {
      isFound = true;
      break;
    }
  }
  [rs close];
  return isFound;
}

id<JavaUtilList> AnUpgradeImpl_getPrivateUpdateKeys(AnUpgradeImpl *self) {
  return JavaUtilArrays_asListWithNSObjectArray_([IOSObjectArray newArrayWithObjects:(id[]){ AnUpgradeImpl_PRIVATE_KEY1, AnUpgradeImpl_PRIVATE_REC_KEY } count:2 type:NSString_class_()]);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(AnUpgradeImpl)

@implementation AnUpgradeImpl_Upgrade

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  AnUpgradeImpl_Upgrade_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (NSString *)getKey {
  return key_;
}

- (void)setKeyWithNSString:(NSString *)key {
  self->key_ = key;
}

- (NSString *)getValue {
  return value_;
}

- (void)setValueWithNSString:(NSString *)value {
  self->value_ = value;
}

- (JavaUtilDate *)getCreateDate {
  return createDate_;
}

- (void)setCreateDateWithJavaUtilDate:(JavaUtilDate *)createDate {
  self->createDate_ = createDate;
}

- (JavaLangInteger *)getStatus {
  return status_;
}

- (void)setStatusWithJavaLangInteger:(JavaLangInteger *)status {
  self->status_ = status;
}

- (JavaLangInteger *)getType {
  return type_;
}

- (void)setTypeWithJavaLangInteger:(JavaLangInteger *)type {
  self->type_ = type;
}

- (JavaLangInteger *)getRefi {
  return refi_;
}

- (void)setRefiWithJavaLangInteger:(JavaLangInteger *)refi {
  self->refi_ = refi;
}

- (JavaLangDouble *)getRefd {
  return refd_;
}

- (void)setRefdWithJavaLangDouble:(JavaLangDouble *)refd {
  self->refd_ = refd;
}

- (JavaLangInteger *)getRefs {
  return refs_;
}

- (void)setRefsWithJavaLangInteger:(JavaLangInteger *)refs {
  self->refs_ = refs;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 2, 1, -1, -1, -1, -1 },
    { NULL, "LJavaUtilDate;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, -1, -1, -1, -1 },
    { NULL, "LJavaLangInteger;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 5, 6, -1, -1, -1, -1 },
    { NULL, "LJavaLangInteger;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 7, 6, -1, -1, -1, -1 },
    { NULL, "LJavaLangInteger;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 8, 6, -1, -1, -1, -1 },
    { NULL, "LJavaLangDouble;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 9, 10, -1, -1, -1, -1 },
    { NULL, "LJavaLangInteger;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 11, 6, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(getKey);
  methods[2].selector = @selector(setKeyWithNSString:);
  methods[3].selector = @selector(getValue);
  methods[4].selector = @selector(setValueWithNSString:);
  methods[5].selector = @selector(getCreateDate);
  methods[6].selector = @selector(setCreateDateWithJavaUtilDate:);
  methods[7].selector = @selector(getStatus);
  methods[8].selector = @selector(setStatusWithJavaLangInteger:);
  methods[9].selector = @selector(getType);
  methods[10].selector = @selector(setTypeWithJavaLangInteger:);
  methods[11].selector = @selector(getRefi);
  methods[12].selector = @selector(setRefiWithJavaLangInteger:);
  methods[13].selector = @selector(getRefd);
  methods[14].selector = @selector(setRefdWithJavaLangDouble:);
  methods[15].selector = @selector(getRefs);
  methods[16].selector = @selector(setRefsWithJavaLangInteger:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "key_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "value_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "createDate_", "LJavaUtilDate;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "status_", "LJavaLangInteger;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "type_", "LJavaLangInteger;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "refi_", "LJavaLangInteger;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "refd_", "LJavaLangDouble;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "refs_", "LJavaLangInteger;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "setKey", "LNSString;", "setValue", "setCreateDate", "LJavaUtilDate;", "setStatus", "LJavaLangInteger;", "setType", "setRefi", "setRefd", "LJavaLangDouble;", "setRefs", "LAnUpgradeImpl;" };
  static const J2ObjcClassInfo _AnUpgradeImpl_Upgrade = { "Upgrade", "com.vals.a2ios.amfibian.impl", ptrTable, methods, fields, 7, 0x9, 17, 8, 12, -1, -1, -1, -1 };
  return &_AnUpgradeImpl_Upgrade;
}

@end

void AnUpgradeImpl_Upgrade_init(AnUpgradeImpl_Upgrade *self) {
  NSObject_init(self);
}

AnUpgradeImpl_Upgrade *new_AnUpgradeImpl_Upgrade_init() {
  J2OBJC_NEW_IMPL(AnUpgradeImpl_Upgrade, init)
}

AnUpgradeImpl_Upgrade *create_AnUpgradeImpl_Upgrade_init() {
  J2OBJC_CREATE_IMPL(AnUpgradeImpl_Upgrade, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(AnUpgradeImpl_Upgrade)
