//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../demo/andr-demo-prj/app/src/main/java/com/prod/vals/andr_demo_prj/Appointment.java
//

#include "J2ObjC_source.h"
#include "com/prod/vals/andr_demo_prj/Appointment.h"
#include "com/prod/vals/andr_demo_prj/Entity.h"
#include "java/lang/Integer.h"

@interface Appointment () {
 @public
  NSString *name_;
  JavaLangInteger *isProcessed_;
}

@end

J2OBJC_FIELD_SETTER(Appointment, name_, NSString *)
J2OBJC_FIELD_SETTER(Appointment, isProcessed_, JavaLangInteger *)

@implementation Appointment

- (NSString *)getName {
  return name_;
}

- (void)setNameWithNSString:(NSString *)name {
  self->name_ = name;
}

- (JavaLangInteger *)getIsProcessed {
  return isProcessed_;
}

- (void)setIsProcessedWithJavaLangInteger:(JavaLangInteger *)isProcessed {
  self->isProcessed_ = isProcessed;
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  Appointment_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getName", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "setNameWithNSString:", "setName", "V", 0x1, NULL, NULL },
    { "getIsProcessed", NULL, "Ljava.lang.Integer;", 0x1, NULL, NULL },
    { "setIsProcessedWithJavaLangInteger:", "setIsProcessed", "V", 0x1, NULL, NULL },
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "name_", NULL, 0x2, "Ljava.lang.String;", NULL, NULL, .constantValue.asLong = 0 },
    { "isProcessed_", NULL, 0x2, "Ljava.lang.Integer;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _Appointment = { 2, "Appointment", "com.prod.vals.andr_demo_prj", NULL, 0x1, 5, methods, 2, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_Appointment;
}

@end

void Appointment_init(Appointment *self) {
  (void) Entity_init(self);
}

Appointment *new_Appointment_init() {
  Appointment *self = [Appointment alloc];
  Appointment_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(Appointment)
