//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../demo/andr-demo-prj/app/src/main/java/com/prod/vals/andr_demo_prj/Appointment.java
//

#include "J2ObjC_source.h"
#include "com/prod/vals/andr_demo_prj/Appointment.h"
#include "com/prod/vals/andr_demo_prj/Entity.h"
#include "java/lang/Integer.h"

@interface Appointment () {
 @public
  NSString *name_;
  JavaLangInteger *isProcessed_;
}

@end

J2OBJC_FIELD_SETTER(Appointment, name_, NSString *)
J2OBJC_FIELD_SETTER(Appointment, isProcessed_, JavaLangInteger *)

@implementation Appointment

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  Appointment_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (NSString *)getName {
  return name_;
}

- (void)setNameWithNSString:(NSString *)name {
  self->name_ = name;
}

- (JavaLangInteger *)getIsProcessed {
  return isProcessed_;
}

- (void)setIsProcessedWithJavaLangInteger:(JavaLangInteger *)isProcessed {
  self->isProcessed_ = isProcessed;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "LJavaLangInteger;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 2, 3, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(getName);
  methods[2].selector = @selector(setNameWithNSString:);
  methods[3].selector = @selector(getIsProcessed);
  methods[4].selector = @selector(setIsProcessedWithJavaLangInteger:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "name_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "isProcessed_", "LJavaLangInteger;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "setName", "LNSString;", "setIsProcessed", "LJavaLangInteger;" };
  static const J2ObjcClassInfo _Appointment = { "Appointment", "com.prod.vals.andr_demo_prj", ptrTable, methods, fields, 7, 0x1, 5, 2, -1, -1, -1, -1, -1 };
  return &_Appointment;
}

@end

void Appointment_init(Appointment *self) {
  Entity_init(self);
}

Appointment *new_Appointment_init() {
  J2OBJC_NEW_IMPL(Appointment, init)
}

Appointment *create_Appointment_init() {
  J2OBJC_CREATE_IMPL(Appointment, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(Appointment)
