//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../demo/andr-demo-prj/app/src/main/java/com/prod/vals/andr_demo_prj/Appointment.java
//

#ifndef _ComProdValsAndr_demo_prjAppointment_H_
#define _ComProdValsAndr_demo_prjAppointment_H_

#include "J2ObjC_header.h"
#include "com/prod/vals/andr_demo_prj/Entity.h"

@class JavaLangInteger;

@interface Appointment : Entity

#pragma mark Public

- (instancetype)init;

- (JavaLangInteger *)getIsProcessed;

- (NSString *)getName;

- (void)setIsProcessedWithJavaLangInteger:(JavaLangInteger *)isProcessed;

- (void)setNameWithNSString:(NSString *)name;

@end

J2OBJC_EMPTY_STATIC_INIT(Appointment)

FOUNDATION_EXPORT void Appointment_init(Appointment *self);

FOUNDATION_EXPORT Appointment *new_Appointment_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(Appointment)

@compatibility_alias ComProdValsAndr_demo_prjAppointment Appointment;

#endif // _ComProdValsAndr_demo_prjAppointment_H_
