//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../demo/andr-demo-prj/app/src/main/java/com/prod/vals/andr_demo_prj/Bootstrap.java
//

#include "J2ObjC_source.h"
#include "com/prod/vals/andr_demo_prj/Bootstrap.h"
#include "com/vals/a2ios/mobilighter/intf/Mobilighter.h"
#include "com/vals/a2ios/sqlighter/intf/SQLighterDb.h"

@interface Bootstrap () {
 @public
  id<SQLighterDb> sqLighterDb_;
  id<Mobilighter> mobilighter_;
}

@end

J2OBJC_FIELD_SETTER(Bootstrap, sqLighterDb_, id<SQLighterDb>)
J2OBJC_FIELD_SETTER(Bootstrap, mobilighter_, id<Mobilighter>)

inline Bootstrap *Bootstrap_get_bootstrap();
inline Bootstrap *Bootstrap_set_bootstrap(Bootstrap *value);
static Bootstrap *Bootstrap_bootstrap;
J2OBJC_STATIC_FIELD_OBJ(Bootstrap, bootstrap, Bootstrap *)

__attribute__((unused)) static void Bootstrap_init(Bootstrap *self);

__attribute__((unused)) static Bootstrap *new_Bootstrap_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static Bootstrap *create_Bootstrap_init();

@implementation Bootstrap

+ (Bootstrap *)getInstance {
  return Bootstrap_getInstance();
}

- (id<SQLighterDb>)getSqLighterDb {
  return sqLighterDb_;
}

- (void)setSqLighterDbWithSQLighterDb:(id<SQLighterDb>)sqLighterDb {
  self->sqLighterDb_ = sqLighterDb;
}

- (id<Mobilighter>)getMobilighter {
  return mobilighter_;
}

- (void)setMobilighterWithMobilighter:(id<Mobilighter>)mobilighter {
  self->mobilighter_ = mobilighter;
}

@end

void Bootstrap_init(Bootstrap *self) {
  NSObject_init(self);
}

Bootstrap *new_Bootstrap_init() {
  J2OBJC_NEW_IMPL(Bootstrap, init)
}

Bootstrap *create_Bootstrap_init() {
  J2OBJC_CREATE_IMPL(Bootstrap, init)
}

Bootstrap *Bootstrap_getInstance() {
  Bootstrap_initialize();
  @synchronized(Bootstrap_class_()) {
    if (Bootstrap_bootstrap == nil) {
      Bootstrap_bootstrap = new_Bootstrap_init();
    }
    return Bootstrap_bootstrap;
  }
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(Bootstrap)
