//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../demo/andr-demo-prj/app/src/main/java/com/prod/vals/andr_demo_prj/Bootstrap.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComProdValsAndr_demo_prjBootstrap")
#ifdef RESTRICT_ComProdValsAndr_demo_prjBootstrap
#define INCLUDE_ALL_ComProdValsAndr_demo_prjBootstrap 0
#else
#define INCLUDE_ALL_ComProdValsAndr_demo_prjBootstrap 1
#endif
#undef RESTRICT_ComProdValsAndr_demo_prjBootstrap

#if !defined (Bootstrap_) && (INCLUDE_ALL_ComProdValsAndr_demo_prjBootstrap || defined(INCLUDE_Bootstrap))
#define Bootstrap_

@protocol Mobilighter;
@protocol SQLighterDb;

@interface Bootstrap : NSObject

#pragma mark Public

+ (Bootstrap *)getInstance;

- (id<Mobilighter>)getMobilighter;

- (id<SQLighterDb>)getSqLighterDb;

- (void)setMobilighterWithMobilighter:(id<Mobilighter>)mobilighter;

- (void)setSqLighterDbWithSQLighterDb:(id<SQLighterDb>)sqLighterDb;

@end

J2OBJC_EMPTY_STATIC_INIT(Bootstrap)

FOUNDATION_EXPORT Bootstrap *Bootstrap_getInstance();

J2OBJC_TYPE_LITERAL_HEADER(Bootstrap)

@compatibility_alias ComProdValsAndr_demo_prjBootstrap Bootstrap;

#endif

#pragma pop_macro("INCLUDE_ALL_ComProdValsAndr_demo_prjBootstrap")
