//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../andr-demo-prj/app/src/main/java/com/prod/vals/andr_demo_prj/Bootstrap.java
//


#include "J2ObjC_source.h"
#include "com/prod/vals/andr_demo_prj/Bootstrap.h"
#include "com/vals/a2ios/sqlighter/intf/SQLighterDb.h"

@interface Bootstrap () {
 @public
  id<SQLighterDb> sqLighterDb_;
}

- (instancetype)init;

@end

J2OBJC_FIELD_SETTER(Bootstrap, sqLighterDb_, id<SQLighterDb>)

static Bootstrap *Bootstrap_bootstrap_;
J2OBJC_STATIC_FIELD_GETTER(Bootstrap, bootstrap_, Bootstrap *)
J2OBJC_STATIC_FIELD_SETTER(Bootstrap, bootstrap_, Bootstrap *)

__attribute__((unused)) static void Bootstrap_init(Bootstrap *self);

__attribute__((unused)) static Bootstrap *new_Bootstrap_init() NS_RETURNS_RETAINED;

@implementation Bootstrap

- (instancetype)init {
  Bootstrap_init(self);
  return self;
}

+ (Bootstrap *)getInstance {
  return Bootstrap_getInstance();
}

- (id<SQLighterDb>)getSqLighterDb {
  return sqLighterDb_;
}

- (void)setSqLighterDbWithSQLighterDb:(id<SQLighterDb>)sqLighterDb {
  self->sqLighterDb_ = sqLighterDb;
}

@end

void Bootstrap_init(Bootstrap *self) {
  (void) NSObject_init(self);
}

Bootstrap *new_Bootstrap_init() {
  Bootstrap *self = [Bootstrap alloc];
  Bootstrap_init(self);
  return self;
}

Bootstrap *Bootstrap_getInstance() {
  Bootstrap_initialize();
  @synchronized(Bootstrap_class_()) {
    if (Bootstrap_bootstrap_ == nil) {
      Bootstrap_bootstrap_ = new_Bootstrap_init();
    }
    return Bootstrap_bootstrap_;
  }
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(Bootstrap)
