//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../demo/andr-demo-prj/app/src/main/java/com/prod/vals/andr_demo_prj/DemoBase.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComProdValsAndr_demo_prjDemoBase")
#ifdef RESTRICT_ComProdValsAndr_demo_prjDemoBase
#define INCLUDE_ALL_ComProdValsAndr_demo_prjDemoBase 0
#else
#define INCLUDE_ALL_ComProdValsAndr_demo_prjDemoBase 1
#endif
#undef RESTRICT_ComProdValsAndr_demo_prjDemoBase

#if !defined (DemoBase_) && (INCLUDE_ALL_ComProdValsAndr_demo_prjDemoBase || defined(INCLUDE_DemoBase))
#define DemoBase_

@class Appointment;
@class IOSClass;
@class JavaLangDouble;
@class JavaLangLong;
@protocol AnIncubator;
@protocol AnOrm;
@protocol JavaUtilCollection;
@protocol MobilAction;
@protocol SQLighterDb;
@protocol SQLighterRs;

@interface DemoBase : NSObject {
 @public
  id sqlighterHelloLabel_;
  id sqlighterDetailsLabel_;
  id amfibianHelloLabel_;
  id amfibianDetailsLabel_;
  id<MobilAction> sqlighterStartAction_;
  id<MobilAction> amfibianStartAction_;
  NSString *jsonStringWithObjectDefinitions_;
  id<AnIncubator> anIncubator_;
}

#pragma mark Public

- (instancetype)init;

- (id<AnOrm>)getOrmWithIOSClass:(IOSClass *)cluss;

#pragma mark Protected

- (void)checkTestWithNSString:(NSString *)name
                  withBoolean:(jboolean)isPassed;

- (void)finishTestWithBoolean:(jboolean)isPassed;

- (void)makeTestsFail;

- (void)printWithAppointment:(Appointment *)appointment;

- (void)printWithJavaUtilCollection:(id<JavaUtilCollection>)appointments;

- (void)printWithSQLighterRs:(id<SQLighterRs>)rs;

- (void)printAppointmentsWithAnOrm:(id<AnOrm>)anOrm;

- (void)printUserTableWithNSString:(NSString *)title
                   withSQLighterDb:(id<SQLighterDb>)db;

- (void)resetTestCounters;

- (void)startTestWithNSString:(NSString *)name;

- (jboolean)testSummaryCheck;

- (jboolean)verifyRecordWithSQLighterRs:(id<SQLighterRs>)rs
                           withNSString:(NSString *)userName
                           withNSString:(NSString *)userEmail
                     withJavaLangDouble:(JavaLangDouble *)userHeight
                           withNSString:(NSString *)blobString
                       withJavaLangLong:(JavaLangLong *)id_;

@end

J2OBJC_EMPTY_STATIC_INIT(DemoBase)

J2OBJC_FIELD_SETTER(DemoBase, sqlighterHelloLabel_, id)
J2OBJC_FIELD_SETTER(DemoBase, sqlighterDetailsLabel_, id)
J2OBJC_FIELD_SETTER(DemoBase, amfibianHelloLabel_, id)
J2OBJC_FIELD_SETTER(DemoBase, amfibianDetailsLabel_, id)
J2OBJC_FIELD_SETTER(DemoBase, sqlighterStartAction_, id<MobilAction>)
J2OBJC_FIELD_SETTER(DemoBase, amfibianStartAction_, id<MobilAction>)
J2OBJC_FIELD_SETTER(DemoBase, jsonStringWithObjectDefinitions_, NSString *)
J2OBJC_FIELD_SETTER(DemoBase, anIncubator_, id<AnIncubator>)

FOUNDATION_EXPORT void DemoBase_init(DemoBase *self);

J2OBJC_TYPE_LITERAL_HEADER(DemoBase)

@compatibility_alias ComProdValsAndr_demo_prjDemoBase DemoBase;

#endif

#pragma pop_macro("INCLUDE_ALL_ComProdValsAndr_demo_prjDemoBase")
