//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../demo/andr-demo-prj/app/src/main/java/com/prod/vals/andr_demo_prj/DemoDefaultGetAdapter.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "com/prod/vals/andr_demo_prj/DemoDefaultGetAdapter.h"
#include "com/vals/a2ios/amfibian/intf/AnAttrib.h"
#include "java/lang/Long.h"
#include "java/util/Date.h"

@implementation DemoDefaultGetAdapter

- (id)convertWithAnAttrib:(id<AnAttrib>)attrib
                   withId:(id)value {
  if (value != nil && [value isKindOfClass:[JavaUtilDate class]]) {
    JavaUtilDate *d = (JavaUtilDate *) check_class_cast(value, [JavaUtilDate class]);
    return new_JavaLangLong_initWithLong_([d getTime]);
  }
  return value;
}

- (void)onWarningWithIOSClass:(IOSClass *)cluss
                 withNSString:(NSString *)attribName
                       withId:(id)value {
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  DemoDefaultGetAdapter_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "convertWithAnAttrib:withId:", "convert", "Ljava.lang.Object;", 0x1, NULL, NULL },
    { "onWarningWithIOSClass:withNSString:withId:", "onWarning", "V", 0x1, NULL, NULL },
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _DemoDefaultGetAdapter = { 2, "DemoDefaultGetAdapter", "com.prod.vals.andr_demo_prj", NULL, 0x1, 3, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_DemoDefaultGetAdapter;
}

@end

void DemoDefaultGetAdapter_init(DemoDefaultGetAdapter *self) {
  (void) NSObject_init(self);
}

DemoDefaultGetAdapter *new_DemoDefaultGetAdapter_init() {
  DemoDefaultGetAdapter *self = [DemoDefaultGetAdapter alloc];
  DemoDefaultGetAdapter_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(DemoDefaultGetAdapter)
