//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../demo/andr-demo-prj/app/src/main/java/com/prod/vals/andr_demo_prj/Demo.java
//

#ifndef _ComProdValsAndr_demo_prjDemo_H_
#define _ComProdValsAndr_demo_prjDemo_H_

#include "J2ObjC_header.h"
#include "com/prod/vals/andr_demo_prj/DemoBase.h"

@protocol AnObject;

@interface Demo : DemoBase

#pragma mark Public

- (instancetype)init;

+ (void)amfibianOperations;

+ (void)anUpdateOperationsWithAnObject:(id<AnObject>)anAppointment;

+ (void)bindUiWithId:(id)title
              withId:(id)sqlighterHelloLabel
              withId:(id)sqlighterDetailsLabel
              withId:(id)sqlighterStartButton
              withId:(id)amfibianHelloLabel
              withId:(id)amfibianDetailsLabel
              withId:(id)amfibianStartButton
              withId:(id)mobilighterCredit;

+ (void)sqlighterOperations;

@end

J2OBJC_EMPTY_STATIC_INIT(Demo)

FOUNDATION_EXPORT void Demo_sqlighterOperations();

FOUNDATION_EXPORT void Demo_amfibianOperations();

FOUNDATION_EXPORT void Demo_anUpdateOperationsWithAnObject_(id<AnObject> anAppointment);

FOUNDATION_EXPORT void Demo_bindUiWithId_withId_withId_withId_withId_withId_withId_withId_(id title, id sqlighterHelloLabel, id sqlighterDetailsLabel, id sqlighterStartButton, id amfibianHelloLabel, id amfibianDetailsLabel, id amfibianStartButton, id mobilighterCredit);

FOUNDATION_EXPORT void Demo_init(Demo *self);

FOUNDATION_EXPORT Demo *new_Demo_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(Demo)

@compatibility_alias ComProdValsAndr_demo_prjDemo Demo;

#endif // _ComProdValsAndr_demo_prjDemo_H_
