//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../demo/andr-demo-prj/app/src/main/java/com/prod/vals/andr_demo_prj/DemoIntGetAdapter.java
//

#ifndef _ComProdValsAndr_demo_prjDemoIntGetAdapter_H_
#define _ComProdValsAndr_demo_prjDemoIntGetAdapter_H_

#include "J2ObjC_header.h"
#include "com/vals/a2ios/amfibian/intf/AnAdapter.h"

@class IOSClass;
@protocol AnAttrib;

@interface DemoIntGetAdapter : NSObject < AnAdapter >

#pragma mark Public

- (instancetype)init;

- (id)convertWithAnAttrib:(id<AnAttrib>)attrib
                   withId:(id)value;

- (void)onWarningWithIOSClass:(IOSClass *)cluss
                 withNSString:(NSString *)attribName
                       withId:(id)value;

@end

J2OBJC_EMPTY_STATIC_INIT(DemoIntGetAdapter)

FOUNDATION_EXPORT void DemoIntGetAdapter_init(DemoIntGetAdapter *self);

FOUNDATION_EXPORT DemoIntGetAdapter *new_DemoIntGetAdapter_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(DemoIntGetAdapter)

@compatibility_alias ComProdValsAndr_demo_prjDemoIntGetAdapter DemoIntGetAdapter;

#endif // _ComProdValsAndr_demo_prjDemoIntGetAdapter_H_
