//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../demo/andr-demo-prj/app/src/main/java/com/prod/vals/andr_demo_prj/DemoIntGetAdapter.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "com/prod/vals/andr_demo_prj/DemoIntGetAdapter.h"
#include "com/vals/a2ios/amfibian/intf/AnAttrib.h"
#include "java/lang/Integer.h"

@implementation DemoIntGetAdapter

- (id)convertWithAnAttrib:(id<AnAttrib>)attrib
                   withId:(id)value {
  jint returnValue = ((value == nil) ? 0 : [(JavaLangInteger *) check_class_cast(value, [JavaLangInteger class]) intValue]);
  return JavaLangInteger_valueOfWithInt_(returnValue);
}

- (void)onWarningWithIOSClass:(IOSClass *)cluss
                 withNSString:(NSString *)attribName
                       withId:(id)value {
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  DemoIntGetAdapter_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "convertWithAnAttrib:withId:", "convert", "Ljava.lang.Object;", 0x1, NULL, NULL },
    { "onWarningWithIOSClass:withNSString:withId:", "onWarning", "V", 0x1, NULL, NULL },
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _DemoIntGetAdapter = { 2, "DemoIntGetAdapter", "com.prod.vals.andr_demo_prj", NULL, 0x1, 3, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_DemoIntGetAdapter;
}

@end

void DemoIntGetAdapter_init(DemoIntGetAdapter *self) {
  (void) NSObject_init(self);
}

DemoIntGetAdapter *new_DemoIntGetAdapter_init() {
  DemoIntGetAdapter *self = [DemoIntGetAdapter alloc];
  DemoIntGetAdapter_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(DemoIntGetAdapter)
