//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../demo/andr-demo-prj/app/src/main/java/com/prod/vals/andr_demo_prj/Entity.java
//

#ifndef _ComProdValsAndr_demo_prjEntity_H_
#define _ComProdValsAndr_demo_prjEntity_H_

#include "J2ObjC_header.h"

@class JavaLangInteger;
@class JavaUtilDate;

@interface Entity : NSObject {
 @public
  JavaLangInteger *id__;
  JavaUtilDate *createDate_;
}

#pragma mark Public

- (instancetype)init;

- (JavaUtilDate *)getCreateDate;

- (JavaLangInteger *)getId;

- (void)setCreateDateWithJavaUtilDate:(JavaUtilDate *)createDate;

- (void)setIdWithJavaLangInteger:(JavaLangInteger *)id_;

@end

J2OBJC_EMPTY_STATIC_INIT(Entity)

J2OBJC_FIELD_SETTER(Entity, id__, JavaLangInteger *)
J2OBJC_FIELD_SETTER(Entity, createDate_, JavaUtilDate *)

FOUNDATION_EXPORT void Entity_init(Entity *self);

FOUNDATION_EXPORT Entity *new_Entity_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(Entity)

@compatibility_alias ComProdValsAndr_demo_prjEntity Entity;

#endif // _ComProdValsAndr_demo_prjEntity_H_
