//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../demo/andr-demo-prj/app/src/main/java/com/prod/vals/andr_demo_prj/Entity.java
//

#include "J2ObjC_source.h"
#include "com/prod/vals/andr_demo_prj/Entity.h"
#include "com/prod/vals/andr_demo_prj/User.h"
#include "java/lang/Integer.h"
#include "java/util/Collection.h"
#include "java/util/Date.h"

@implementation Entity

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  Entity_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (JavaLangInteger *)getId {
  return id__;
}

- (void)setIdWithJavaLangInteger:(JavaLangInteger *)id_ {
  self->id__ = id_;
}

- (JavaUtilDate *)getCreateDate {
  return createDate_;
}

- (void)setCreateDateWithJavaUtilDate:(JavaUtilDate *)createDate {
  self->createDate_ = createDate;
}

- (JavaLangInteger *)getStatus {
  return status_;
}

- (void)setStatusWithJavaLangInteger:(JavaLangInteger *)status {
  self->status_ = status;
}

- (JavaLangInteger *)getType {
  return type_;
}

- (void)setTypeWithJavaLangInteger:(JavaLangInteger *)type {
  self->type_ = type;
}

- (JavaLangInteger *)getCreateUserId {
  return createUserId_;
}

- (void)setCreateUserIdWithJavaLangInteger:(JavaLangInteger *)createUserId {
  self->createUserId_ = createUserId;
}

- (User *)getCreateUser {
  return createUser_;
}

- (void)setCreateUserWithUser:(User *)createUser {
  self->createUser_ = createUser;
}

- (id<JavaUtilCollection>)getAppointments {
  return appointments_;
}

- (void)setAppointmentsWithJavaUtilCollection:(id<JavaUtilCollection>)appointments {
  self->appointments_ = appointments;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaLangInteger;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "LJavaUtilDate;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 2, 3, -1, -1, -1, -1 },
    { NULL, "LJavaLangInteger;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 4, 1, -1, -1, -1, -1 },
    { NULL, "LJavaLangInteger;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 5, 1, -1, -1, -1, -1 },
    { NULL, "LJavaLangInteger;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 6, 1, -1, -1, -1, -1 },
    { NULL, "LUser;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 7, 8, -1, -1, -1, -1 },
    { NULL, "LJavaUtilCollection;", 0x1, -1, -1, -1, 9, -1, -1 },
    { NULL, "V", 0x1, 10, 11, -1, 12, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(getId);
  methods[2].selector = @selector(setIdWithJavaLangInteger:);
  methods[3].selector = @selector(getCreateDate);
  methods[4].selector = @selector(setCreateDateWithJavaUtilDate:);
  methods[5].selector = @selector(getStatus);
  methods[6].selector = @selector(setStatusWithJavaLangInteger:);
  methods[7].selector = @selector(getType);
  methods[8].selector = @selector(setTypeWithJavaLangInteger:);
  methods[9].selector = @selector(getCreateUserId);
  methods[10].selector = @selector(setCreateUserIdWithJavaLangInteger:);
  methods[11].selector = @selector(getCreateUser);
  methods[12].selector = @selector(setCreateUserWithUser:);
  methods[13].selector = @selector(getAppointments);
  methods[14].selector = @selector(setAppointmentsWithJavaUtilCollection:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "id__", "LJavaLangInteger;", .constantValue.asLong = 0, 0x1, 13, -1, -1, -1 },
    { "createDate_", "LJavaUtilDate;", .constantValue.asLong = 0, 0x1, -1, -1, -1, -1 },
    { "status_", "LJavaLangInteger;", .constantValue.asLong = 0, 0x1, -1, -1, -1, -1 },
    { "type_", "LJavaLangInteger;", .constantValue.asLong = 0, 0x1, -1, -1, -1, -1 },
    { "createUserId_", "LJavaLangInteger;", .constantValue.asLong = 0, 0x1, -1, -1, -1, -1 },
    { "createUser_", "LUser;", .constantValue.asLong = 0, 0x1, -1, -1, -1, -1 },
    { "appointments_", "LJavaUtilCollection;", .constantValue.asLong = 0, 0x1, -1, -1, 14, -1 },
  };
  static const void *ptrTable[] = { "setId", "LJavaLangInteger;", "setCreateDate", "LJavaUtilDate;", "setStatus", "setType", "setCreateUserId", "setCreateUser", "LUser;", "()Ljava/util/Collection<Lcom/prod/vals/andr_demo_prj/Appointment;>;", "setAppointments", "LJavaUtilCollection;", "(Ljava/util/Collection<Lcom/prod/vals/andr_demo_prj/Appointment;>;)V", "id", "Ljava/util/Collection<Lcom/prod/vals/andr_demo_prj/Appointment;>;" };
  static const J2ObjcClassInfo _Entity = { "Entity", "com.prod.vals.andr_demo_prj", ptrTable, methods, fields, 7, 0x1, 15, 7, -1, -1, -1, -1, -1 };
  return &_Entity;
}

@end

void Entity_init(Entity *self) {
  NSObject_init(self);
}

Entity *new_Entity_init() {
  J2OBJC_NEW_IMPL(Entity, init)
}

Entity *create_Entity_init() {
  J2OBJC_CREATE_IMPL(Entity, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(Entity)
