//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../demo/andr-demo-prj/app/src/main/java/com/prod/vals/andr_demo_prj/Entity.java
//

#include "J2ObjC_source.h"
#include "com/prod/vals/andr_demo_prj/Entity.h"
#include "java/lang/Integer.h"
#include "java/util/Date.h"

@implementation Entity

- (JavaLangInteger *)getId {
  return id__;
}

- (void)setIdWithJavaLangInteger:(JavaLangInteger *)id_ {
  self->id__ = id_;
}

- (JavaUtilDate *)getCreateDate {
  return createDate_;
}

- (void)setCreateDateWithJavaUtilDate:(JavaUtilDate *)createDate {
  self->createDate_ = createDate;
}

- (JavaLangInteger *)getStatus {
  return status_;
}

- (void)setStatusWithJavaLangInteger:(JavaLangInteger *)status {
  self->status_ = status;
}

- (JavaLangInteger *)getType {
  return type_;
}

- (void)setTypeWithJavaLangInteger:(JavaLangInteger *)type {
  self->type_ = type;
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  Entity_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getId", NULL, "Ljava.lang.Integer;", 0x1, NULL, NULL },
    { "setIdWithJavaLangInteger:", "setId", "V", 0x1, NULL, NULL },
    { "getCreateDate", NULL, "Ljava.util.Date;", 0x1, NULL, NULL },
    { "setCreateDateWithJavaUtilDate:", "setCreateDate", "V", 0x1, NULL, NULL },
    { "getStatus", NULL, "Ljava.lang.Integer;", 0x1, NULL, NULL },
    { "setStatusWithJavaLangInteger:", "setStatus", "V", 0x1, NULL, NULL },
    { "getType", NULL, "Ljava.lang.Integer;", 0x1, NULL, NULL },
    { "setTypeWithJavaLangInteger:", "setType", "V", 0x1, NULL, NULL },
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "id__", "id", 0x1, "Ljava.lang.Integer;", NULL, NULL, .constantValue.asLong = 0 },
    { "createDate_", NULL, 0x1, "Ljava.util.Date;", NULL, NULL, .constantValue.asLong = 0 },
    { "status_", NULL, 0x1, "Ljava.lang.Integer;", NULL, NULL, .constantValue.asLong = 0 },
    { "type_", NULL, 0x1, "Ljava.lang.Integer;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _Entity = { 2, "Entity", "com.prod.vals.andr_demo_prj", NULL, 0x1, 9, methods, 4, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_Entity;
}

@end

void Entity_init(Entity *self) {
  (void) NSObject_init(self);
}

Entity *new_Entity_init() {
  Entity *self = [Entity alloc];
  Entity_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(Entity)
