//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../demo/andr-demo-prj/app/src/main/java/com/prod/vals/andr_demo_prj/User.java
//

#ifndef _ComProdValsAndr_demo_prjUser_H_
#define _ComProdValsAndr_demo_prjUser_H_

#include "J2ObjC_header.h"
#include "com/prod/vals/andr_demo_prj/Entity.h"

@protocol JavaUtilCollection;

@interface User : Entity

#pragma mark Public

- (instancetype)init;

- (id<JavaUtilCollection>)getAppointments;

- (NSString *)getName;

- (void)setAppointmentsWithJavaUtilCollection:(id<JavaUtilCollection>)appointments;

- (void)setNameWithNSString:(NSString *)name;

@end

J2OBJC_EMPTY_STATIC_INIT(User)

FOUNDATION_EXPORT void User_init(User *self);

FOUNDATION_EXPORT User *new_User_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(User)

@compatibility_alias ComProdValsAndr_demo_prjUser User;

#endif // _ComProdValsAndr_demo_prjUser_H_
