//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../demo/andr-demo-prj/app/src/main/java/com/prod/vals/andr_demo_prj/User.java
//

#include "J2ObjC_source.h"
#include "com/prod/vals/andr_demo_prj/Entity.h"
#include "com/prod/vals/andr_demo_prj/User.h"
#include "java/util/Collection.h"

@interface User () {
 @public
  NSString *name_;
  id<JavaUtilCollection> appointments_User_;
}

@end

J2OBJC_FIELD_SETTER(User, name_, NSString *)
J2OBJC_FIELD_SETTER(User, appointments_User_, id<JavaUtilCollection>)

@implementation User

- (NSString *)getName {
  return name_;
}

- (void)setNameWithNSString:(NSString *)name {
  self->name_ = name;
}

- (id<JavaUtilCollection>)getAppointments {
  return appointments_User_;
}

- (void)setAppointmentsWithJavaUtilCollection:(id<JavaUtilCollection>)appointments {
  self->appointments_User_ = appointments;
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  User_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getName", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "setNameWithNSString:", "setName", "V", 0x1, NULL, NULL },
    { "getAppointments", NULL, "Ljava.util.Collection;", 0x1, NULL, NULL },
    { "setAppointmentsWithJavaUtilCollection:", "setAppointments", "V", 0x1, NULL, NULL },
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "name_", NULL, 0x2, "Ljava.lang.String;", NULL, NULL, .constantValue.asLong = 0 },
    { "appointments_User_", "appointments", 0x2, "Ljava.util.Collection;", NULL, "Ljava/util/Collection<Lcom/prod/vals/andr_demo_prj/Appointment;>;", .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _User = { 2, "User", "com.prod.vals.andr_demo_prj", NULL, 0x1, 5, methods, 2, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_User;
}

@end

void User_init(User *self) {
  (void) Entity_init(self);
}

User *new_User_init() {
  User *self = [User alloc];
  User_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(User)
