//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../../android//com/vals/a2ios/amfibian/impl/AnAttribImpl.java
//

#ifndef _ComValsA2iosAmfibianImplAnAttribImpl_H_
#define _ComValsA2iosAmfibianImplAnAttribImpl_H_

#include "J2ObjC_header.h"
#include "com/vals/a2ios/amfibian/intf/AnAttrib.h"

@class IOSClass;
@class JavaLangReflectMethod;
@protocol AnObject;

@interface AnAttribImpl : NSObject < AnAttrib > {
 @public
  NSString *defaultConverterKey_;
  NSString *defaultGetConverterKey_;
}

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)attribColumnJsonName;

- (instancetype)initWithNSString:(NSString *)attribName
                    withNSString:(NSString *)columnName
                    withNSString:(NSString *)jsonName;

- (void)clearCustomGetConverters;

- (void)clearCustomSetConverters;

- (IOSClass *)getAttribClass;

- (NSString *)getAttribName;

- (NSString *)getColumnName;

- (NSString *)getColumnOrAttribName;

- (id<AnAttrib_CustomConverter>)getCustomGetConverter;

- (id<AnAttrib_CustomConverter>)getCustomGetConverterWithNSString:(NSString *)key;

- (id<AnAttrib_CustomConverter>)getCustomSetConverter;

- (id<AnAttrib_CustomConverter>)getCustomSetConverterWithNSString:(NSString *)key;

- (NSString *)getDbColumnDefinition;

- (JavaLangReflectMethod *)getGetter;

- (NSString *)getJsonOrAttribName;

- (JavaLangReflectMethod *)getSetter;

- (id)getValue;

- (void)setAnObjectWithAnObject:(id<AnObject>)anObject;

- (void)setAttribNameWithNSString:(NSString *)attribName;

- (void)setColumnNameWithNSString:(NSString *)columnName;

- (void)setCustomGetConverterWithAnAttrib_CustomConverter:(id<AnAttrib_CustomConverter>)converter;

- (void)setCustomGetConverterWithNSString:(NSString *)key
             withAnAttrib_CustomConverter:(id<AnAttrib_CustomConverter>)converter;

- (void)setCustomSetConverterWithAnAttrib_CustomConverter:(id<AnAttrib_CustomConverter>)converter;

- (void)setCustomSetConverterWithNSString:(NSString *)key
             withAnAttrib_CustomConverter:(id<AnAttrib_CustomConverter>)converter;

- (void)setDbColumnDefinitionWithNSString:(NSString *)dbColumnDefinition;

- (void)setDefaultGetConversionKeyWithNSString:(NSString *)key;

- (void)setDefaultSetConversionKeyWithNSString:(NSString *)key;

- (void)setValueWithId:(id)value;

@end

J2OBJC_EMPTY_STATIC_INIT(AnAttribImpl)

J2OBJC_FIELD_SETTER(AnAttribImpl, defaultConverterKey_, NSString *)
J2OBJC_FIELD_SETTER(AnAttribImpl, defaultGetConverterKey_, NSString *)

FOUNDATION_EXPORT NSString *AnAttribImpl_NONAME_CONVERSION_KEY_;
J2OBJC_STATIC_FIELD_GETTER(AnAttribImpl, NONAME_CONVERSION_KEY_, NSString *)

FOUNDATION_EXPORT void AnAttribImpl_initWithNSString_withNSString_withNSString_(AnAttribImpl *self, NSString *attribName, NSString *columnName, NSString *jsonName);

FOUNDATION_EXPORT AnAttribImpl *new_AnAttribImpl_initWithNSString_withNSString_withNSString_(NSString *attribName, NSString *columnName, NSString *jsonName) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void AnAttribImpl_initWithNSString_(AnAttribImpl *self, NSString *attribColumnJsonName);

FOUNDATION_EXPORT AnAttribImpl *new_AnAttribImpl_initWithNSString_(NSString *attribColumnJsonName) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(AnAttribImpl)

@compatibility_alias ComValsA2iosAmfibianImplAnAttribImpl AnAttribImpl;

#endif // _ComValsA2iosAmfibianImplAnAttribImpl_H_
