//
//  ViewController.m
//  ios-demo-prj
//
//  Created by Vlad Sayenko on 8/27/15.
//  Copyright (c) 2015 Vlad Sayenko. All rights reserved.
//

#import "ViewController.h"
#import "Demo.h"

@interface ViewController ()

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.
    
    /**
     * Start demo. Demo.h and Demo.m are automatically generated by j2objc.
     *
     */
    greetLabel.text = [Demo sqlighterOperations];
    
    meetAmfibianLabel.text = [Demo amfibianOperations];
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

@end
